// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // bag_type
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class bag_type
    {
        public int bgtyp_nr { get; set; } // bgtyp_nr (Primary key)
        public string descript { get; set; } // descript (length: 60)
        public decimal max_val_bag { get; set; } // max_val_bag
        public decimal def_val_bag { get; set; } // def_val_bag
        public string abbrev { get; set; } // abbrev (length: 8)
        public decimal max_weight_bag { get; set; } // max_weight_bag
        public decimal def_weight_bag { get; set; } // def_weight_bag
        public string barcd_ident { get; set; } // barcd_ident (length: 30)
        public bool? repack { get; set; } // repack
        public System.Guid UID { get; set; } // UID
        public int WP_MaxProductQuantity { get; set; } // WP_MaxProductQuantity
        public bool IsAllocationBySize { get; set; } // IsAllocationBySize
        public bool IsAtmCassette { get; set; } // IsAtmCassette
        public int id { get; set; } // id

        public bag_type()
        {
            max_val_bag = 0m;
            def_val_bag = 0m;
            max_weight_bag = 0m;
            def_weight_bag = 0m;
            UID = System.Guid.NewGuid();
            WP_MaxProductQuantity = 0;
            IsAllocationBySize = false;
            IsAtmCassette = false;
        }
    }

}
// </auto-generated>
