// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Currency
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class CurrencyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Currency>
    {
        public CurrencyConfiguration()
            : this("dbo")
        {
        }

        public CurrencyConfiguration(string schema)
        {
            ToTable("Currency", schema);
            HasKey(x => x.curCode);

            Property(x => x.curCode).HasColumnName(@"curCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(3).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.curDesc).HasColumnName(@"curDesc").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.curdecimals).HasColumnName(@"curdecimals").HasColumnType("int").IsOptional();
            Property(x => x.WP_CoinName).HasColumnName(@"WP_CoinName").HasColumnType("nvarchar").IsOptional().HasMaxLength(30);
            Property(x => x.WP_CoinsName).HasColumnName(@"WP_CoinsName").HasColumnType("nvarchar").IsOptional().HasMaxLength(30);
            Property(x => x.UID).HasColumnName(@"UID").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.WP_Default).HasColumnName(@"WP_Default").HasColumnType("bit").IsRequired();
            Property(x => x.IsEnabled).HasColumnName(@"IsEnabled").HasColumnType("bit").IsRequired();
            Property(x => x.NumericCode).HasColumnName(@"NumericCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(3);
            Property(x => x.IsDomestic).HasColumnName(@"IsDomestic").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
