// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_Billing_BillingJobSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_Billing_BillingJobSettingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Cwc_Billing_BillingJobSetting>
    {
        public Cwc_Billing_BillingJobSettingConfiguration()
            : this("dbo")
        {
        }

        public Cwc_Billing_BillingJobSettingConfiguration(string schema)
        {
            ToTable("Cwc_Billing_BillingJobSettings", schema);
            HasKey(x => new { x.BillingDailyAtTime, x.IsAffectServicePerPeriodAllCustomers, x.id, x.IsSaveBillingLinesWithZeroValue, x.IsJobBusy, x.IsBillCollectedTransportOrder });

            Property(x => x.BillingDailyAtTime).HasColumnName(@"BillingDailyAtTime").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.LastBilledDate).HasColumnName(@"LastBilledDate").HasColumnType("datetime").IsOptional();
            Property(x => x.IsAffectServicePerPeriodAllCustomers).HasColumnName(@"IsAffectServicePerPeriodAllCustomers").HasColumnType("bit").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.UserBillingDateTime).HasColumnName(@"UserBillingDateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IsSaveBillingLinesWithZeroValue).HasColumnName(@"IsSaveBillingLinesWithZeroValue").HasColumnType("bit").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IsJobBusy).HasColumnName(@"IsJobBusy").HasColumnType("bit").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IsBillCollectedTransportOrder).HasColumnName(@"IsBillCollectedTransportOrder").HasColumnType("bit").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
        }
    }

}
// </auto-generated>
