// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_Billing_BillingLineHistoricalFields
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_Billing_BillingLineHistoricalFieldConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Cwc_Billing_BillingLineHistoricalField>
    {
        public Cwc_Billing_BillingLineHistoricalFieldConfiguration()
            : this("dbo")
        {
        }

        public Cwc_Billing_BillingLineHistoricalFieldConfiguration(string schema)
        {
            ToTable("Cwc_Billing_BillingLineHistoricalFields", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IsCancelledService).HasColumnName(@"IsCancelledService").HasColumnType("bit").IsRequired();
            Property(x => x.Type).HasColumnName(@"Type").HasColumnType("int").IsRequired();
            Property(x => x.OrderLineID).HasColumnName(@"OrderLineID").HasColumnType("nvarchar").IsOptional().HasMaxLength(20);
            Property(x => x.ContractLineID).HasColumnName(@"ContractLineID").HasColumnType("int").IsOptional();
            Property(x => x.ScheduleLineID).HasColumnName(@"ScheduleLineID").HasColumnType("int").IsOptional();
            Property(x => x.ContractedJobID).HasColumnName(@"ContractedJobID").HasColumnType("int").IsOptional();
            Property(x => x.ContractedProductID).HasColumnName(@"ContractedProductID").HasColumnType("int").IsOptional();
            Property(x => x.SLAPenaltyID).HasColumnName(@"SLAPenaltyID").HasColumnType("int").IsOptional();
            Property(x => x.ContractLocationGroupID).HasColumnName(@"ContractLocationGroupID").HasColumnType("int").IsOptional();
            Property(x => x.VisitPriceID).HasColumnName(@"VisitPriceID").HasColumnType("int").IsOptional();
            Property(x => x.StockOrderID).HasColumnName(@"StockOrderID").HasColumnType("bigint").IsOptional();
            Property(x => x.CashCenterContractLineID).HasColumnName(@"CashCenterContractLineID").HasColumnType("int").IsOptional();
            Property(x => x.ContractedCountID).HasColumnName(@"ContractedCountID").HasColumnType("int").IsOptional();
            Property(x => x.BillingLineID).HasColumnName(@"BillingLineID").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
