// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_Transport_ServicingTimeWindowsExportJobSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_Transport_ServicingTimeWindowsExportJobSetting
    {
        public int id { get; set; } // id (Primary key)
        public int WorkingFolderType { get; set; } // WorkingFolderType
        public string WorkingFolderPath { get; set; } // WorkingFolderPath (length: 255)
        public string FtpLogin { get; set; } // FtpLogin
        public string FtpPassword { get; set; } // FtpPassword (length: 255)

        public Cwc_Transport_ServicingTimeWindowsExportJobSetting()
        {
            WorkingFolderType = 1;
        }
    }

}
// </auto-generated>
