// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_Transport_CitExportDataSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_Transport_CitExportDataSettingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Cwc_Transport_CitExportDataSetting>
    {
        public Cwc_Transport_CitExportDataSettingConfiguration()
            : this("dbo")
        {
        }

        public Cwc_Transport_CitExportDataSettingConfiguration(string schema)
        {
            ToTable("Cwc_Transport_CitExportDataSettings", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IsExportFile).HasColumnName(@"IsExportFile").HasColumnType("bit").IsRequired();
            Property(x => x.ExportFileTime).HasColumnName(@"ExportFileTime").HasColumnType("float").IsRequired();
            Property(x => x.ExportFilePrefix).HasColumnName(@"ExportFilePrefix").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.ExportFileFolder).HasColumnName(@"ExportFileFolder").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
        }
    }

}
// </auto-generated>
