// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_TransportInterface_TransportIntegrationSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_TransportInterface_TransportIntegrationSettingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Cwc_TransportInterface_TransportIntegrationSetting>
    {
        public Cwc_TransportInterface_TransportIntegrationSettingConfiguration()
            : this("dbo")
        {
        }

        public Cwc_TransportInterface_TransportIntegrationSettingConfiguration(string schema)
        {
            ToTable("Cwc_TransportInterface_TransportIntegrationSettings", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.GetImportFilesFolder).HasColumnName(@"GetImportFilesFolder").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.PutExportFilesFolder).HasColumnName(@"PutExportFilesFolder").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.EnableImport).HasColumnName(@"EnableImport").HasColumnType("bit").IsRequired();
            Property(x => x.EnableExport).HasColumnName(@"EnableExport").HasColumnType("bit").IsRequired();
            Property(x => x.EnableExportPackage).HasColumnName(@"EnableExportPackage").HasColumnType("bit").IsRequired();
            Property(x => x.TimeExportPackage).HasColumnName(@"TimeExportPackage").HasColumnType("float").IsOptional();
            Property(x => x.IsEnableLooseProductExport).HasColumnName(@"IsEnableLooseProductExport").HasColumnType("bit").IsRequired();
            Property(x => x.TimeLooseProductExport).HasColumnName(@"TimeLooseProductExport").HasColumnType("int").IsOptional();
            Property(x => x.IsEnableDispatchExport).HasColumnName(@"IsEnableDispatchExport").HasColumnType("bit").IsRequired();
            Property(x => x.TimeDispatchExport).HasColumnName(@"TimeDispatchExport").HasColumnType("int").IsOptional();
            Property(x => x.DispatchExportFilesFolder).HasColumnName(@"DispatchExportFilesFolder").HasColumnType("nvarchar").IsOptional().HasMaxLength(256);
            Property(x => x.PackageStartExport).HasColumnName(@"PackageStartExport").HasColumnType("date").IsRequired();
            Property(x => x.LooseProductStartExport).HasColumnName(@"LooseProductStartExport").HasColumnType("date").IsRequired();
            Property(x => x.DispatchStartExport).HasColumnName(@"DispatchStartExport").HasColumnType("date").IsRequired();
        }
    }

}
// </auto-generated>
