// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_Integration_OrderImportFormatB_OrderImportFormatBJobPostcodeLink
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_Integration_OrderImportFormatB_OrderImportFormatBJobPostcodeLinkConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Cwc_Integration_OrderImportFormatB_OrderImportFormatBJobPostcodeLink>
    {
        public Cwc_Integration_OrderImportFormatB_OrderImportFormatBJobPostcodeLinkConfiguration()
            : this("dbo")
        {
        }

        public Cwc_Integration_OrderImportFormatB_OrderImportFormatBJobPostcodeLinkConfiguration(string schema)
        {
            ToTable("Cwc_Integration_OrderImportFormatB_OrderImportFormatBJobPostcodeLink", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PostAreaCodeFrom).HasColumnName(@"PostAreaCodeFrom").HasColumnType("int").IsRequired();
            Property(x => x.PostLetterCodeFrom).HasColumnName(@"PostLetterCodeFrom").HasColumnType("nvarchar").IsRequired().HasMaxLength(2);
            Property(x => x.PostAreaCodeTo).HasColumnName(@"PostAreaCodeTo").HasColumnType("int").IsRequired();
            Property(x => x.PostLetterCodeTo).HasColumnName(@"PostLetterCodeTo").HasColumnType("nvarchar").IsRequired().HasMaxLength(2);
            Property(x => x.IsAllowBankHoliday).HasColumnName(@"IsAllowBankHoliday").HasColumnType("bit").IsRequired();
            Property(x => x.DefaultCitSiteID).HasColumnName(@"DefaultCitSiteID").HasColumnType("int").IsRequired();
            Property(x => x.NotesCCSiteID).HasColumnName(@"NotesCCSiteID").HasColumnType("int").IsRequired();
            Property(x => x.CoinsCCSiteID).HasColumnName(@"CoinsCCSiteID").HasColumnType("int").IsRequired();
            Property(x => x.NotesCCStreamID).HasColumnName(@"NotesCCStreamID").HasColumnType("int").IsOptional();
            Property(x => x.CoinsCCStreamID).HasColumnName(@"CoinsCCStreamID").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
