// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_CashCenter_InternalProcessingJobPreannouncementReroutingLog
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_CashCenter_InternalProcessingJobPreannouncementReroutingLog
    {
        public int id { get; set; } // id (Primary key)
        public System.DateTime DateCreated { get; set; } // DateCreated
        public int Result { get; set; } // Result
        public string Message { get; set; } // Message (length: 1024)
        public int? LocationToID { get; set; } // LocationToID
        public int LocationToNewID { get; set; } // LocationToNewID
        public string StockContainerNumber { get; set; } // StockContainerNumber (length: 100)
        public int? StockContainerPreannouncementType { get; set; } // StockContainerPreannouncementType

        public Cwc_CashCenter_InternalProcessingJobPreannouncementReroutingLog()
        {
            DateCreated = System.DateTime.Now;
            Result = 0;
        }
    }

}
// </auto-generated>
