// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_Transport_PackageLifeCycleProcessedItem
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_Transport_PackageLifeCycleProcessedItemConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Cwc_Transport_PackageLifeCycleProcessedItem>
    {
        public Cwc_Transport_PackageLifeCycleProcessedItemConfiguration()
            : this("dbo")
        {
        }

        public Cwc_Transport_PackageLifeCycleProcessedItemConfiguration(string schema)
        {
            ToTable("Cwc_Transport_PackageLifeCycleProcessedItem", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PackageLifeCycleID).HasColumnName(@"PackageLifeCycleID").HasColumnType("int").IsRequired();
            Property(x => x.IsProcessedForServiceOrder).HasColumnName(@"IsProcessedForServiceOrder").HasColumnType("bit").IsRequired();
            Property(x => x.IsProcessedForTransportOrder).HasColumnName(@"IsProcessedForTransportOrder").HasColumnType("bit").IsRequired();
            Property(x => x.IsProcessedReassigned).HasColumnName(@"IsProcessedReassigned").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
