// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_Transport_CitProcessSettingServicingTimeWindow
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_Transport_CitProcessSettingServicingTimeWindow
    {
        public int id { get; set; } // id (Primary key)
        public int? OrderType { get; set; } // OrderType
        public double TimeFrom { get; set; } // TimeFrom
        public double TimeTo { get; set; } // TimeTo
        public int Weekday { get; set; } // Weekday
        public int CitProcessSettingID { get; set; } // CitProcessSettingID
        public int? ServiceTypeID { get; set; } // ServiceTypeID
        public bool IsDefault { get; set; } // IsDefault
        public System.TimeSpan? TimeSecondFrom { get; set; } // TimeSecondFrom
        public System.TimeSpan? TimeSecondTo { get; set; } // TimeSecondTo
        public System.DateTime DateCreated { get; set; } // DateCreated
        public System.DateTime DateUpdated { get; set; } // DateUpdated
        public int? AuthorID { get; set; } // AuthorID
        public int? EditorID { get; set; } // EditorID

        public Cwc_Transport_CitProcessSettingServicingTimeWindow()
        {
            TimeFrom = 0;
            IsDefault = false;
            DateCreated = System.DateTime.Now;
            DateUpdated = System.DateTime.Now;
        }
    }

}
// </auto-generated>
