// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_Transport_CitProcessingHistoryException
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_Transport_CitProcessingHistoryExceptionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Cwc_Transport_CitProcessingHistoryException>
    {
        public Cwc_Transport_CitProcessingHistoryExceptionConfiguration()
            : this("dbo")
        {
        }

        public Cwc_Transport_CitProcessingHistoryExceptionConfiguration(string schema)
        {
            ToTable("Cwc_Transport_CitProcessingHistoryException", schema);
            HasKey(x => x.ID);

            Property(x => x.ID).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("int").IsRequired();
            Property(x => x.Remark).HasColumnName(@"Remark").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.DateResolved).HasColumnName(@"DateResolved").HasColumnType("datetime").IsOptional();
            Property(x => x.Action).HasColumnName(@"Action").HasColumnType("int").IsOptional();
            Property(x => x.ExceptionCaseID).HasColumnName(@"ExceptionCaseID").HasColumnType("int").IsRequired();
            Property(x => x.CitProcessingHistoryID).HasColumnName(@"CitProcessingHistoryID").HasColumnType("int").IsRequired();
            Property(x => x.SiteID).HasColumnName(@"SiteID").HasColumnType("int").IsRequired();
            Property(x => x.WorkstationID).HasColumnName(@"WorkstationID").HasColumnType("int").IsOptional();
            Property(x => x.ResolvedByID).HasColumnName(@"ResolvedByID").HasColumnType("int").IsOptional();
            Property(x => x.SecondUserID).HasColumnName(@"SecondUserID").HasColumnType("int").IsOptional();
            Property(x => x.ReasonCodeID).HasColumnName(@"ReasonCodeID").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
