// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_CashCenter_InternalProcessingJobScheduleSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_CashCenter_InternalProcessingJobScheduleSettingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Cwc_CashCenter_InternalProcessingJobScheduleSetting>
    {
        public Cwc_CashCenter_InternalProcessingJobScheduleSettingConfiguration()
            : this("dbo")
        {
        }

        public Cwc_CashCenter_InternalProcessingJobScheduleSettingConfiguration(string schema)
        {
            ToTable("Cwc_CashCenter_InternalProcessingJobScheduleSettings", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Type).HasColumnName(@"Type").HasColumnType("int").IsRequired();
            Property(x => x.IsEnabled).HasColumnName(@"IsEnabled").HasColumnType("bit").IsRequired();
            Property(x => x.ExecuteDate).HasColumnName(@"ExecuteDate").HasColumnType("datetime").IsOptional();
            Property(x => x.TimeStart).HasColumnName(@"TimeStart").HasColumnType("time").IsRequired();
            Property(x => x.TimeEnd).HasColumnName(@"TimeEnd").HasColumnType("time").IsRequired();
            Property(x => x.Periodicity).HasColumnName(@"Periodicity").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
