// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_Billing_BillingJobLog
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_Billing_BillingJobLog
    {
        public int id { get; set; } // id (Primary key)
        public System.DateTime DateCreated { get; set; } // DateCreated
        public System.DateTime DateUpdated { get; set; } // DateUpdated
        public int Result { get; set; } // Result
        public string Message { get; set; } // Message
        public int? PriceRule { get; set; } // PriceRule
        public int? UnitOfMeasure { get; set; } // UnitOfMeasure
        public string ContractNumber { get; set; } // ContractNumber (length: 256)
        public int TotalLines { get; set; } // TotalLines
        public bool IsRebilling { get; set; } // IsRebilling
        public int? CompanyID { get; set; } // CompanyID
        public decimal? TotalUnits { get; set; } // TotalUnits

        public Cwc_Billing_BillingJobLog()
        {
            DateCreated = System.DateTime.Now;
            TotalLines = 0;
            IsRebilling = false;
            TotalUnits = 0m;
        }
    }

}
// </auto-generated>
