// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_Integration_OrderImportFormatB_OrderImportFormatBJobPostcodeWeekdayLink
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_Integration_OrderImportFormatB_OrderImportFormatBJobPostcodeWeekdayLinkConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Cwc_Integration_OrderImportFormatB_OrderImportFormatBJobPostcodeWeekdayLink>
    {
        public Cwc_Integration_OrderImportFormatB_OrderImportFormatBJobPostcodeWeekdayLinkConfiguration()
            : this("dbo")
        {
        }

        public Cwc_Integration_OrderImportFormatB_OrderImportFormatBJobPostcodeWeekdayLinkConfiguration(string schema)
        {
            ToTable("Cwc_Integration_OrderImportFormatB_OrderImportFormatBJobPostcodeWeekdayLink", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Weekday).HasColumnName(@"Weekday").HasColumnType("int").IsRequired();
            Property(x => x.OrderImportFormatBJobPostcodeLinkID).HasColumnName(@"OrderImportFormatBJobPostcodeLinkID").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
