// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_BaseData_ConfigurationKey
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_BaseData_ConfigurationKeyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Cwc_BaseData_ConfigurationKey>
    {
        public Cwc_BaseData_ConfigurationKeyConfiguration()
            : this("dbo")
        {
        }

        public Cwc_BaseData_ConfigurationKeyConfiguration(string schema)
        {
            ToTable("Cwc_BaseData_ConfigurationKey", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("int").IsRequired();
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.Value).HasColumnName(@"Value").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.IsMandatory).HasColumnName(@"IsMandatory").HasColumnType("bit").IsRequired();
            Property(x => x.DataType).HasColumnName(@"DataType").HasColumnType("int").IsRequired();
            Property(x => x.IsMasterConfiguration).HasColumnName(@"IsMasterConfiguration").HasColumnType("bit").IsRequired();
            Property(x => x.DateCreated).HasColumnName(@"DateCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.DateUpdated).HasColumnName(@"DateUpdated").HasColumnType("datetime").IsRequired();
            Property(x => x.AuthorID).HasColumnName(@"AuthorID").HasColumnType("int").IsOptional();
            Property(x => x.EditorID).HasColumnName(@"EditorID").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
