// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_Contracts_PriceLine
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_Contracts_PriceLine
    {
        public int id { get; set; } // id (Primary key)
        public bool IsLatestRevision { get; set; } // IsLatestRevision
        public int? RevisionNumber { get; set; } // RevisionNumber
        public System.DateTime? RevisionDate { get; set; } // RevisionDate
        public int? ReplacedRevisionNumber { get; set; } // ReplacedRevisionNumber
        public System.DateTime? ReplacedRevisionDate { get; set; } // ReplacedRevisionDate
        public int? AuthorID { get; set; } // AuthorID
        public int ContractID { get; set; } // ContractID
        public int PriceRule { get; set; } // PriceRule
        public int UnitOfMeasure { get; set; } // UnitOfMeasure
        public string ConfigurationLevelsMask { get; set; } // ConfigurationLevelsMask (length: 1024)
        public string ReferenceCode { get; set; } // ReferenceCode (length: 25)
        public string Description { get; set; } // Description (length: 50)
        public decimal Units { get; set; } // Units
        public decimal Price { get; set; } // Price
        public decimal? MinBillableUnits { get; set; } // MinBillableUnits
        public decimal? MaxBillableUnits { get; set; } // MaxBillableUnits
        public bool IsApplySurcharges { get; set; } // IsApplySurcharges
        public bool IsDecreasePriceProportionally { get; set; } // IsDecreasePriceProportionally
        public bool IsRangePriceBasedOnTotal { get; set; } // IsRangePriceBasedOnTotal
        public int? DebtorID { get; set; } // DebtorID
        public int? BankAccountID { get; set; } // BankAccountID
        public int? LatestRevisionID { get; set; } // LatestRevisionID
        public System.Guid UID { get; set; } // UID
        public decimal? VatPercentage { get; set; } // VatPercentage

        public Cwc_Contracts_PriceLine()
        {
            IsLatestRevision = true;
            Units = 1m;
            Price = 0m;
            IsApplySurcharges = false;
            IsDecreasePriceProportionally = true;
            IsRangePriceBasedOnTotal = true;
            UID = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
