// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_Transport_PackageLifeCycleProcessingJobSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_Transport_PackageLifeCycleProcessingJobSetting
    {
        public int id { get; set; } // id (Primary key)
        public System.DateTime? PreviousStarted { get; set; } // PreviousStarted
        public System.DateTime? LastStarted { get; set; } // LastStarted
        public System.DateTime? LastEnded { get; set; } // LastEnded
    }

}
// </auto-generated>
