// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_Transport_CitProcessingHistory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_Transport_CitProcessingHistoryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Cwc_Transport_CitProcessingHistory>
    {
        public Cwc_Transport_CitProcessingHistoryConfiguration()
            : this("dbo")
        {
        }

        public Cwc_Transport_CitProcessingHistoryConfiguration(string schema)
        {
            ToTable("Cwc_Transport_CitProcessingHistory", schema);
            HasKey(x => x.ID);

            Property(x => x.ID).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ProcessName).HasColumnName(@"ProcessName").HasColumnType("int").IsOptional();
            Property(x => x.ProcessPhase).HasColumnName(@"ProcessPhase").HasColumnType("int").IsOptional();
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("int").IsRequired();
            Property(x => x.IsWithException).HasColumnName(@"IsWithException").HasColumnType("bit").IsOptional();
            Property(x => x.DateCreated).HasColumnName(@"DateCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.ObjectID).HasColumnName(@"ObjectID").HasColumnType("int").IsRequired();
            Property(x => x.ObjectClassID).HasColumnName(@"ObjectClassID").HasColumnType("int").IsRequired();
            Property(x => x.AuthorID).HasColumnName(@"AuthorID").HasColumnType("int").IsOptional();
            Property(x => x.WorkstationID).HasColumnName(@"WorkstationID").HasColumnType("int").IsOptional();
            Property(x => x.ReferToObjectID).HasColumnName(@"ReferToObjectID").HasColumnType("int").IsOptional();
            Property(x => x.ReferToObjectClassID).HasColumnName(@"ReferToObjectClassID").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
