// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_BaseData_ContactPersonLink
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_BaseData_ContactPersonLinkConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Cwc_BaseData_ContactPersonLink>
    {
        public Cwc_BaseData_ContactPersonLinkConfiguration()
            : this("dbo")
        {
        }

        public Cwc_BaseData_ContactPersonLinkConfiguration(string schema)
        {
            ToTable("Cwc_BaseData_ContactPersonLink", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IsPrimary).HasColumnName(@"IsPrimary").HasColumnType("bit").IsRequired();
            Property(x => x.ContactPersonID).HasColumnName(@"ContactPersonID").HasColumnType("int").IsRequired();
            Property(x => x.ObjectID).HasColumnName(@"ObjectID").HasColumnType("int").IsRequired();
            Property(x => x.ObjectClassID).HasColumnName(@"ObjectClassID").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
