// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_Forecast_TurnoverPercentageSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_Forecast_TurnoverPercentageSetting
    {
        public int id { get; set; } // id (Primary key)
        public int Weekday { get; set; } // Weekday
        public int ServiceDateType { get; set; } // ServiceDateType
        public int TurnoverPercentage { get; set; } // TurnoverPercentage
        public int OptimizationSettingsID { get; set; } // OptimizationSettingsID

        public Cwc_Forecast_TurnoverPercentageSetting()
        {
            Weekday = 0;
            ServiceDateType = 0;
            TurnoverPercentage = 100;
        }
    }

}
// </auto-generated>
