// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_Transport_ServicingTimeWindowsExportItem
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_Transport_ServicingTimeWindowsExportItemConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Cwc_Transport_ServicingTimeWindowsExportItem>
    {
        public Cwc_Transport_ServicingTimeWindowsExportItemConfiguration()
            : this("dbo")
        {
        }

        public Cwc_Transport_ServicingTimeWindowsExportItemConfiguration(string schema)
        {
            ToTable("Cwc_Transport_ServicingTimeWindowsExportItem", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.FileName).HasColumnName(@"FileName").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.CitProcessSettingID).HasColumnName(@"CitProcessSettingID").HasColumnType("int").IsOptional();
            Property(x => x.CitProcessSettingLinkID).HasColumnName(@"CitProcessSettingLinkID").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
