// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_Integration_OrderImportFormatB_OrderImportFormatBJobSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_Integration_OrderImportFormatB_OrderImportFormatBJobSetting
    {
        public int id { get; set; } // id (Primary key)
        public string PostcodesIncomingFileFolder { get; set; } // PostcodesIncomingFileFolder (length: 255)
        public string IncomingFileFolder { get; set; } // IncomingFileFolder (length: 255)
        public string IncomingFilePrefix { get; set; } // IncomingFilePrefix (length: 10)
        public int LastFileSequenceNumber { get; set; } // LastFileSequenceNumber
        public bool IsCreateVisitAddress { get; set; } // IsCreateVisitAddress
        public string VisitAddressPrefix { get; set; } // VisitAddressPrefix (length: 5)
        public string VisitAddressSuffixMask { get; set; } // VisitAddressSuffixMask (length: 10)
        public int VisitAddressLastSuffix { get; set; } // VisitAddressLastSuffix
        public string ServicePointPrefix { get; set; } // ServicePointPrefix (length: 5)
        public string ServicePointSuffixMask { get; set; } // ServicePointSuffixMask (length: 10)
        public int ServicePointLastSuffix { get; set; } // ServicePointLastSuffix
        public string OutgoingFileFolder { get; set; } // OutgoingFileFolder (length: 255)
        public string OutgoingFilePrefix { get; set; } // OutgoingFilePrefix (length: 10)
        public int? CompanyID { get; set; } // CompanyID
        public int? OrderingDepartmentID { get; set; } // OrderingDepartmentID
        public int? ServiceTypeID { get; set; } // ServiceTypeID
        public int? LocationTypeID { get; set; } // LocationTypeID
        public string HandlingTypeID { get; set; } // HandlingTypeID (length: 6)
        public int? CashPointTypeID { get; set; } // CashPointTypeID

        public Cwc_Integration_OrderImportFormatB_OrderImportFormatBJobSetting()
        {
            LastFileSequenceNumber = 0;
            IsCreateVisitAddress = false;
            VisitAddressLastSuffix = 1;
            ServicePointLastSuffix = 1;
        }
    }

}
// </auto-generated>
