// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_Transport_CitProcessSetting
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_Transport_CitProcessSetting
    {
        public int id { get; set; } // id (Primary key)
        public System.DateTime DateCreated { get; set; } // DateCreated
        public System.DateTime DateUpdated { get; set; } // DateUpdated
        public int? AuthorID { get; set; } // AuthorID
        public int? EditorID { get; set; } // EditorID
        public decimal? CustomerID { get; set; } // CustomerID
        public int? LocationTypeID { get; set; } // LocationTypeID
        public decimal? ServicePointID { get; set; } // ServicePointID
        public int BasicStopDuration { get; set; } // BasicStopDuration
        public bool IsServicing24x7 { get; set; } // IsServicing24x7
        public int? CashPointTypeID { get; set; } // CashPointTypeID
        public decimal? VisitAddressID { get; set; } // VisitAddressID
        public bool IsNotifyUponReschedule { get; set; } // IsNotifyUponReschedule
        public int? OnHoldDaysNumber { get; set; } // OnHoldDaysNumber
        public bool IsAdditionalDeliveryRequired { get; set; } // IsAdditionalDeliveryRequired
        public int? DefaultAdditionalDeliveryServiceTypeId { get; set; } // DefaultAdditionalDeliveryServiceTypeId
        public bool IsDefault { get; set; } // IsDefault

        public Cwc_Transport_CitProcessSetting()
        {
            DateCreated = System.DateTime.Now;
            DateUpdated = System.DateTime.Now;
            BasicStopDuration = 0;
            IsServicing24x7 = true;
            IsNotifyUponReschedule = false;
            IsAdditionalDeliveryRequired = false;
            IsDefault = false;
        }
    }

}
// </auto-generated>
