// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_Integration_OrderImportFormatA_OrderImportFormatAJobSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_Integration_OrderImportFormatA_OrderImportFormatAJobSettingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Cwc_Integration_OrderImportFormatA_OrderImportFormatAJobSetting>
    {
        public Cwc_Integration_OrderImportFormatA_OrderImportFormatAJobSettingConfiguration()
            : this("dbo")
        {
        }

        public Cwc_Integration_OrderImportFormatA_OrderImportFormatAJobSettingConfiguration(string schema)
        {
            ToTable("Cwc_Integration_OrderImportFormatA_OrderImportFormatAJobSettings", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IncomingFileFolder).HasColumnName(@"IncomingFileFolder").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.IsJobBusy).HasColumnName(@"IsJobBusy").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
