// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_Transport_PackageLifeCycleProcessingJobLog
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_Transport_PackageLifeCycleProcessingJobLog
    {
        public int id { get; set; } // id (Primary key)
        public int Result { get; set; } // Result
        public int Action { get; set; } // Action
        public string Message { get; set; } // Message (length: 255)
        public int PackageLifeCycleId { get; set; } // PackageLifeCycleId
        public int? TransportOrderOldId { get; set; } // TransportOrderOldId
        public int? TransportOrderNewId { get; set; } // TransportOrderNewId
        public int? ServiceOrderNewId { get; set; } // ServiceOrderNewId
        public System.DateTime? DateCreated { get; set; } // DateCreated
        public System.DateTime? DateUpdated { get; set; } // DateUpdated
        public int? AuthorID { get; set; } // AuthorID
        public int? EditorID { get; set; } // EditorID

        public Cwc_Transport_PackageLifeCycleProcessingJobLog()
        {
            Result = 0;
        }
    }

}
// </auto-generated>
