// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_BaseData_ProductMaterialLink
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_BaseData_ProductMaterialLinkConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Cwc_BaseData_ProductMaterialLink>
    {
        public Cwc_BaseData_ProductMaterialLinkConfiguration()
            : this("dbo")
        {
        }

        public Cwc_BaseData_ProductMaterialLinkConfiguration(string schema)
        {
            ToTable("Cwc_BaseData_ProductMaterialLink", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.NumberOfItems).HasColumnName(@"NumberOfItems").HasColumnType("int").IsRequired();
            Property(x => x.MaterialID).HasColumnName(@"MaterialID").HasColumnType("int").IsRequired();
            Property(x => x.ProductID).HasColumnName(@"ProductID").HasColumnType("int").IsRequired();
            Property(x => x.UID).HasColumnName(@"UID").HasColumnType("uniqueidentifier").IsRequired();
        }
    }

}
// </auto-generated>
