// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_Transport_TransportOrder
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_Transport_TransportOrder
    {
        public int id { get; set; } // id (Primary key)
        public string Code { get; set; } // Code (length: 255)
        public string ReferenceCode { get; set; } // ReferenceCode (length: 30)
        public int OrderType { get; set; } // OrderType
        public System.DateTime TransportDate { get; set; } // TransportDate
        public System.DateTime? ServiceDate { get; set; } // ServiceDate
        public int Status { get; set; } // Status
        public bool IsWithException { get; set; } // IsWithException
        public bool IsPdaAdHoc { get; set; } // IsPdaAdHoc
        public string MasterRouteCode { get; set; } // MasterRouteCode (length: 255)
        public System.DateTime? MasterRouteDate { get; set; } // MasterRouteDate
        public System.TimeSpan? StopArrivalTime { get; set; } // StopArrivalTime
        public int? VisitSequence { get; set; } // VisitSequence
        public bool IsBillable { get; set; } // IsBillable
        public int ServiceTypeID { get; set; } // ServiceTypeID
        public int SiteID { get; set; } // SiteID
        public decimal? LocationID { get; set; } // LocationID
        public string LocationPickUpCode { get; set; } // LocationPickUpCode (length: 64)
        public string ServiceOrderID { get; set; } // ServiceOrderID (length: 255)
        public int? PDAReasonCodeID { get; set; } // PDAReasonCodeID
        public System.DateTime DateCreated { get; set; } // DateCreated
        public System.DateTime DateUpdated { get; set; } // DateUpdated
        public int? EditorID { get; set; } // EditorID
        public int? AuthorID { get; set; } // AuthorID
        public int? CollectServiceTypeId { get; set; } // CollectServiceTypeId
        public int? DeliveryServiceTypeId { get; set; } // DeliveryServiceTypeId
        public int? ServicingServiceTypeId { get; set; } // ServicingServiceTypeId
        public bool IsOnHold { get; set; } // IsOnHold
        public System.DateTime? DatePuttedOnHold { get; set; } // DatePuttedOnHold
        public bool IsNewTransportOrderRequired { get; set; } // IsNewTransportOrderRequired
        public string OldTransportOrderCode { get; set; } // OldTransportOrderCode (length: 255)
        public System.Guid UID { get; set; } // UID
        public string CitReference { get; set; } // CitReference (length: 30)

        public Cwc_Transport_TransportOrder()
        {
            Status = 0;
            IsWithException = false;
            IsPdaAdHoc = false;
            IsBillable = true;
            IsOnHold = false;
            IsNewTransportOrderRequired = false;
            UID = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
