// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Cwc_CashCenter_InternalProcessingJobScheduleSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Cwc_CashCenter_InternalProcessingJobScheduleSetting
    {
        public int id { get; set; } // id (Primary key)
        public int Type { get; set; } // Type
        public bool IsEnabled { get; set; } // IsEnabled
        public System.DateTime? ExecuteDate { get; set; } // ExecuteDate
        public System.TimeSpan TimeStart { get; set; } // TimeStart
        public System.TimeSpan TimeEnd { get; set; } // TimeEnd
        public int Periodicity { get; set; } // Periodicity

        public Cwc_CashCenter_InternalProcessingJobScheduleSetting()
        {
            IsEnabled = false;
        }
    }

}
// </auto-generated>
