// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // dai_coin
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class dai_coinConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<dai_coin>
    {
        public dai_coinConfiguration()
            : this("dbo")
        {
        }

        public dai_coinConfiguration(string schema)
        {
            ToTable("dai_coin", schema);
            HasKey(x => x.id);

            Property(x => x.dai_date).HasColumnName(@"dai_date").HasColumnType("datetime").IsRequired();
            Property(x => x.day_nr).HasColumnName(@"day_nr").HasColumnType("int").IsRequired();
            Property(x => x.time_a).HasColumnName(@"time_a").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.coin_nr).HasColumnName(@"coin_nr").HasColumnType("int").IsRequired();
            Property(x => x.loc_nr).HasColumnName(@"loc_nr").HasColumnType("decimal").IsRequired().HasPrecision(18,0);
            Property(x => x.coin_amt_del).HasColumnName(@"coin_amt_del").HasColumnType("int").IsOptional();
            Property(x => x.coin_amt_col).HasColumnName(@"coin_amt_col").HasColumnType("int").IsOptional();
            Property(x => x.total_value_col).HasColumnName(@"total_value_col").HasColumnType("decimal").IsOptional().HasPrecision(26,8);
            Property(x => x.total_value_del).HasColumnName(@"total_value_del").HasColumnType("decimal").IsOptional().HasPrecision(26,8);
            Property(x => x.numtype).HasColumnName(@"numtype").HasColumnType("int").IsRequired();
            Property(x => x.reason_mc).HasColumnName(@"reason_mc").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.reason_cd_mc).HasColumnName(@"reason_cd_mc").HasColumnType("int").IsOptional();
            Property(x => x.branch_cd).HasColumnName(@"branch_cd").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.mast_cd).HasColumnName(@"mast_cd").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.UID).HasColumnName(@"UID").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
        }
    }

}
// </auto-generated>
