// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // dai_coin
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class dai_coin
    {
        public System.DateTime dai_date { get; set; } // dai_date
        public int day_nr { get; set; } // day_nr
        public string time_a { get; set; } // time_a (length: 10)
        public int coin_nr { get; set; } // coin_nr
        public decimal loc_nr { get; set; } // loc_nr
        public int? coin_amt_del { get; set; } // coin_amt_del
        public int? coin_amt_col { get; set; } // coin_amt_col
        public decimal? total_value_col { get; set; } // total_value_col
        public decimal? total_value_del { get; set; } // total_value_del
        public int numtype { get; set; } // numtype
        public string reason_mc { get; set; } // reason_mc (length: 50)
        public int? reason_cd_mc { get; set; } // reason_cd_mc
        public string branch_cd { get; set; } // branch_cd (length: 10)
        public string mast_cd { get; set; } // mast_cd (length: 10)
        public System.Guid UID { get; set; } // UID
        public int id { get; set; } // id (Primary key)

        public dai_coin()
        {
            UID = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
