// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // loc_serv
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class loc_serv
    {
        public decimal? loc_nr { get; set; } // loc_nr
        public int day_nr { get; set; } // day_nr
        public int? mast_nr { get; set; } // mast_nr
        public int? bgtyp_nr { get; set; } // bgtyp_nr
        public string serv_type { get; set; } // serv_type (length: 60)
        public decimal? to_loc_nr { get; set; } // to_loc_nr
        public string a_time { get; set; } // a_time (length: 10)
        public decimal? revenue { get; set; } // revenue
        public int? msg_nr { get; set; } // msg_nr
        public string s_time { get; set; } // s_time (length: 10)
        public string loc_timew1 { get; set; } // loc_timew1 (length: 60)
        public string loc_timew2 { get; set; } // loc_timew2 (length: 60)
        public decimal? max_val { get; set; } // max_val
        public string contr_nr { get; set; } // contr_nr (length: 40)
        public int? serv_nr { get; set; } // serv_nr
        public bool? initiator { get; set; } // initiator
        public System.DateTime? import_date { get; set; } // import_date
        public decimal? amt { get; set; } // amt
        public int? frequency { get; set; } // frequency
        public int? freq_week { get; set; } // freq_week
        public int? freq_recur { get; set; } // freq_recur
        public int? freq_month { get; set; } // freq_month
        public System.DateTime? startdate { get; set; } // startdate
        public System.DateTime? enddate { get; set; } // enddate
        public int? branch_nr { get; set; } // branch_nr
        public string WP_ServiceTypeCode { get; set; } // WP_ServiceTypeCode (length: 255)
        public System.Guid UID { get; set; } // UID (Primary key via unique index idx_loc_serv_UID)
        public string WP_servCodes { get; set; } // WP_servCodes (length: 255)
        public string WP_mast_cd { get; set; } // WP_mast_cd (length: 255)
        public System.DateTime WP_DateCreated { get; set; } // WP_DateCreated

        public loc_serv()
        {
            UID = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
