// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // LocationType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class LocationType
    {
        public string ltCode { get; set; } // ltCode (length: 16)
        public string ltDesc { get; set; } // ltDesc (length: 80)
        public string prcatCode { get; set; } // prcatCode (length: 16)
        public System.Guid UID { get; set; } // UID
        public int id { get; set; } // id (Primary key)
        public int? Category { get; set; } // Category

        public LocationType()
        {
            UID = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
