// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Material
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Material
    {
        public string materialID { get; set; } // materialID (length: 10)
        public int? materialNum { get; set; } // materialNum
        public string MaterialDesc { get; set; } // MaterialDesc (length: 30)
        public string matTypeCode { get; set; } // matTypeCode (length: 10)
        public string curCode { get; set; } // curCode (length: 3)
        public decimal? denomination { get; set; } // denomination
        public decimal? weight { get; set; } // weight
        public int WP_id { get; set; } // WP_id (Primary key)
        public System.Guid UID { get; set; } // UID
        public int? MaximumValue { get; set; } // MaximumValue
        public string ReferenceCode { get; set; } // ReferenceCode (length: 255)

        public Material()
        {
            UID = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
