// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // ProdComposition
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class ProdCompositionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ProdComposition>
    {
        public ProdCompositionConfiguration()
            : this("dbo")
        {
        }

        public ProdCompositionConfiguration(string schema)
        {
            ToTable("ProdComposition", schema);
            HasKey(x => x.id);

            Property(x => x.ProdCodeWhole).HasColumnName(@"ProdCodeWhole").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.ProdCodePart).HasColumnName(@"ProdCodePart").HasColumnType("nvarchar").IsRequired().HasMaxLength(10);
            Property(x => x.numItems).HasColumnName(@"numItems").HasColumnType("int").IsOptional();
            Property(x => x.UID).HasColumnName(@"UID").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
        }
    }

}
// </auto-generated>
