// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // Product
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Product
    {
        public string ProductCode { get; set; } // ProductCode (length: 10)
        public string productDesc { get; set; } // productDesc (length: 30)
        public string prodTypeCode { get; set; } // prodTypeCode (length: 10)
        public string WP_ArticleCode { get; set; } // WP_ArticleCode (length: 128)
        public string WP_UnitName { get; set; } // WP_UnitName (length: 30)
        public string WP_UnitsName { get; set; } // WP_UnitsName (length: 30)
        public decimal? WP_Value { get; set; } // WP_Value
        public string WP_CurrencyCode { get; set; } // WP_CurrencyCode (length: 3)
        public int WP_id { get; set; } // WP_id (Primary key)
        public decimal? WP_Denomination { get; set; } // WP_Denomination
        public System.DateTime? WP_AvailableFrom { get; set; } // WP_AvailableFrom
        public System.DateTime? WP_AvailableTo { get; set; } // WP_AvailableTo
        public int? WP_MaximumQty { get; set; } // WP_MaximumQty
        public System.Guid UID { get; set; } // UID
        public bool IsStockUnit { get; set; } // IsStockUnit
        public bool IsCustomerUnit { get; set; } // IsCustomerUnit
        public bool IsInternalUnit { get; set; } // IsInternalUnit
        public bool IsSupplyUnit { get; set; } // IsSupplyUnit
        public decimal WP_Weight { get; set; } // WP_Weight
        public decimal WP_WrappingWeight { get; set; } // WP_WrappingWeight
        public bool IsBarcodedProduct { get; set; } // IsBarcodedProduct
        public int? BagTypeId { get; set; } // BagTypeId
        public int? ProductGroupId { get; set; } // ProductGroupId

        public Product()
        {
            WP_Value = 0m;
            WP_Denomination = 0m;
            UID = System.Guid.NewGuid();
            IsStockUnit = false;
            IsCustomerUnit = false;
            IsInternalUnit = false;
            IsSupplyUnit = false;
            WP_Weight = 0m;
            WP_WrappingWeight = 0m;
            IsBarcodedProduct = false;
        }
    }

}
// </auto-generated>
