// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // SOProduct
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class SOProductConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SOProduct>
    {
        public SOProductConfiguration()
            : this("dbo")
        {
        }

        public SOProductConfiguration(string schema)
        {
            ToTable("SOProduct", schema);
            HasKey(x => x.id);

            Property(x => x.Orderline_ID).HasColumnName(@"Orderline_ID").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ProductCode).HasColumnName(@"ProductCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(20);
            Property(x => x.OrderProduct_Number).HasColumnName(@"OrderProduct_Number").HasColumnType("int").IsOptional();
            Property(x => x.OrderProduct_Value).HasColumnName(@"OrderProduct_Value").HasColumnType("decimal").IsOptional().HasPrecision(26,8);
            Property(x => x.Actual_Number).HasColumnName(@"Actual_Number").HasColumnType("int").IsOptional();
            Property(x => x.Actual_Value).HasColumnName(@"Actual_Value").HasColumnType("decimal").IsOptional().HasPrecision(26,8);
            Property(x => x.WP_prean_qty).HasColumnName(@"WP_prean_qty").HasColumnType("int").IsOptional();
            Property(x => x.WP_prean_value).HasColumnName(@"WP_prean_value").HasColumnType("decimal").IsOptional().HasPrecision(26,8);
            Property(x => x.WP_count_date).HasColumnName(@"WP_count_date").HasColumnType("datetime").IsOptional();
            Property(x => x.WP_pack_nr).HasColumnName(@"WP_pack_nr").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.WP_material_id).HasColumnName(@"WP_material_id").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.WP_booking_date).HasColumnName(@"WP_booking_date").HasColumnType("datetime").IsOptional();
            Property(x => x.WP_total_only).HasColumnName(@"WP_total_only").HasColumnType("bit").IsRequired();
            Property(x => x.WP_reject).HasColumnName(@"WP_reject").HasColumnType("bit").IsRequired();
            Property(x => x.WP_ref_loc_nr).HasColumnName(@"WP_ref_loc_nr").HasColumnType("nvarchar").IsOptional().HasMaxLength(64);
            Property(x => x.WP_Submit_Date).HasColumnName(@"WP_Submit_Date").HasColumnType("datetime").IsOptional();
            Property(x => x.UID).HasColumnName(@"UID").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.WP_Picked_Qty).HasColumnName(@"WP_Picked_Qty").HasColumnType("int").IsOptional();
            Property(x => x.WP_Picked_Value).HasColumnName(@"WP_Picked_Value").HasColumnType("decimal").IsOptional().HasPrecision(18,0);
            Property(x => x.WP_Picked_Date).HasColumnName(@"WP_Picked_Date").HasColumnType("datetime").IsOptional();
            Property(x => x.CurrencyID).HasColumnName(@"CurrencyID").HasColumnType("nvarchar").IsRequired().HasMaxLength(3);
            Property(x => x.id).HasColumnName(@"id").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IsLoose).HasColumnName(@"IsLoose").HasColumnType("bit").IsRequired();
            Property(x => x.ExpectedResidualValue).HasColumnName(@"ExpectedResidualValue").HasColumnType("decimal").IsOptional().HasPrecision(18,2);
            Property(x => x.ExpectedResidualQuantity).HasColumnName(@"ExpectedResidualQuantity").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
