// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_Archiving_ArchivingSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_Archiving_ArchivingSettingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_Archiving_ArchivingSetting>
    {
        public WP_Archiving_ArchivingSettingConfiguration()
            : this("dbo")
        {
        }

        public WP_Archiving_ArchivingSettingConfiguration(string schema)
        {
            ToTable("WP_Archiving_ArchivingSettings", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.Default).HasColumnName(@"Default").HasColumnType("bit").IsRequired();
            Property(x => x.Inherited).HasColumnName(@"Inherited").HasColumnType("bit").IsRequired();
            Property(x => x.ClearRule).HasColumnName(@"ClearRule").HasColumnType("int").IsOptional();
            Property(x => x.ClearDays).HasColumnName(@"ClearDays").HasColumnType("int").IsOptional();
            Property(x => x.ClearSize).HasColumnName(@"ClearSize").HasColumnType("int").IsOptional();
            Property(x => x.ArchiveClearRule).HasColumnName(@"ArchiveClearRule").HasColumnType("int").IsOptional();
            Property(x => x.ArchiveClearingDate).HasColumnName(@"ArchiveClearingDate").HasColumnType("datetime").IsOptional();
            Property(x => x.TopLevelSettingsID).HasColumnName(@"TopLevelSettingsID").HasColumnType("int").IsOptional();
            Property(x => x.ArchivingManager).HasColumnName(@"ArchivingManager").HasColumnType("nvarchar").IsOptional().HasMaxLength(1000);
            Property(x => x.InheritedArchiving).HasColumnName(@"InheritedArchiving").HasColumnType("bit").IsRequired();
            Property(x => x.ArchivingTopLevelSettingsID).HasColumnName(@"ArchivingTopLevelSettingsID").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
