// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_AutomatedOrderCreationSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_AutomatedOrderCreationSetting
    {
        public int Id { get; set; } // Id (Primary key)
        public bool EnabledConfirmation { get; set; } // EnabledConfirmation
        public bool EnabledAutomatedOrderCreation { get; set; } // EnabledAutomatedOrderCreation

        public WP_AutomatedOrderCreationSetting()
        {
            EnabledConfirmation = false;
            EnabledAutomatedOrderCreation = false;
        }
    }

}
// </auto-generated>
