// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_AfwaSettingCustomerLinks
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_AfwaSettingCustomerLinkConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_AfwaSettingCustomerLink>
    {
        public WP_AfwaSettingCustomerLinkConfiguration()
            : this("dbo")
        {
        }

        public WP_AfwaSettingCustomerLinkConfiguration(string schema)
        {
            ToTable("WP_AfwaSettingCustomerLinks", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.AfwaSettingID).HasColumnName(@"AfwaSettingID").HasColumnType("int").IsRequired();
            Property(x => x.CustomerID).HasColumnName(@"CustomerID").HasColumnType("numeric").IsRequired().HasPrecision(15,0);
        }
    }

}
// </auto-generated>
