// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_AliveMachines
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_AliveMachineConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_AliveMachine>
    {
        public WP_AliveMachineConfiguration()
            : this("dbo")
        {
        }

        public WP_AliveMachineConfiguration(string schema)
        {
            ToTable("WP_AliveMachines", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.MachineId).HasColumnName(@"MachineId").HasColumnType("int").IsRequired();
            Property(x => x.GetAliveStatusTime).HasColumnName(@"GetAliveStatusTime").HasColumnType("datetime").IsRequired();
            Property(x => x.ProcessTime).HasColumnName(@"ProcessTime").HasColumnType("datetime").IsRequired();
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("int").IsOptional();
            Property(x => x.SubStatus).HasColumnName(@"SubStatus").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
        }
    }

}
// </auto-generated>
