// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_Asset
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_Asset
    {
        public int id { get; set; } // id
        public string AssetID { get; set; } // AssetID (Primary key) (length: 255)
        public string PackageID { get; set; } // PackageID (length: 25)
        public int Status { get; set; } // Status
        public System.DateTime? LastMaintenanceDate { get; set; } // LastMaintenanceDate
        public System.DateTime? NextMaintenanceStart { get; set; } // NextMaintenanceStart
        public System.DateTime? NextMaintenanceEnd { get; set; } // NextMaintenanceEnd
        public System.DateTime? DetonationDate { get; set; } // DetonationDate
        public System.DateTime? ScrapDate { get; set; } // ScrapDate
        public string Description { get; set; } // Description (length: 255)
        public string Apportionment { get; set; } // Apportionment (length: 255)
        public System.DateTime DateCreated { get; set; } // DateCreated
        public System.DateTime DateUpdated { get; set; } // DateUpdated
        public decimal Customer_id { get; set; } // Customer_id
        public int? MaintenanceLocation_id { get; set; } // MaintenanceLocation_id
        public int? AssetGroup_id { get; set; } // AssetGroup_id
        public string PartOf_AssetID { get; set; } // PartOf_AssetID (length: 255)
        public string ReplacedWith_AssetID { get; set; } // ReplacedWith_AssetID (length: 255)
        public int? Manufacturer_id { get; set; } // Manufacturer_id
        public int? Denomination_id { get; set; } // Denomination_id
        public int? Region_id { get; set; } // Region_id
        public int Author_id { get; set; } // Author_id
        public int Editor_id { get; set; } // Editor_id
    }

}
// </auto-generated>
