// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_AliveStatusMonitorSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_AliveStatusMonitorSetting
    {
        public int id { get; set; } // id (Primary key)
        public bool Enabled { get; set; } // Enabled
        public int Time { get; set; } // Time
        public int? Status { get; set; } // Status
        public string SubStatus { get; set; } // SubStatus (length: 255)
        public string Description { get; set; } // Description (length: 255)

        public WP_AliveStatusMonitorSetting()
        {
            Enabled = false;
            Time = 10;
        }
    }

}
// </auto-generated>
