// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_BaseData_Country
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_BaseData_CountryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_BaseData_Country>
    {
        public WP_BaseData_CountryConfiguration()
            : this("dbo")
        {
        }

        public WP_BaseData_CountryConfiguration(string schema)
        {
            ToTable("WP_BaseData_Country", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CountryName).HasColumnName(@"CountryName").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.LetterCode).HasColumnName(@"LetterCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(2);
            Property(x => x.IBANFormatID).HasColumnName(@"IBANFormatID").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
