// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_BaseData_ProductionMachine
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_BaseData_ProductionMachineConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_BaseData_ProductionMachine>
    {
        public WP_BaseData_ProductionMachineConfiguration()
            : this("dbo")
        {
        }

        public WP_BaseData_ProductionMachineConfiguration(string schema)
        {
            ToTable("WP_BaseData_ProductionMachine", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Number).HasColumnName(@"Number").HasColumnType("nvarchar").IsRequired().HasMaxLength(30);
            Property(x => x.Group).HasColumnName(@"Group").HasColumnType("int").IsRequired();
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("int").IsRequired();
            Property(x => x.IsUnfitDetection).HasColumnName(@"IsUnfitDetection").HasColumnType("bit").IsRequired();
            Property(x => x.DateCreated).HasColumnName(@"DateCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.DateUpdated).HasColumnName(@"DateUpdated").HasColumnType("datetime").IsOptional();
            Property(x => x.ConnectionType).HasColumnName(@"ConnectionType").HasColumnType("int").IsOptional();
            Property(x => x.ComPort).HasColumnName(@"ComPort").HasColumnType("nvarchar").IsOptional().HasMaxLength(20);
            Property(x => x.BpsRate).HasColumnName(@"BpsRate").HasColumnType("nvarchar").IsOptional().HasMaxLength(20);
            Property(x => x.DataBits).HasColumnName(@"DataBits").HasColumnType("nvarchar").IsOptional().HasMaxLength(20);
            Property(x => x.StopBits).HasColumnName(@"StopBits").HasColumnType("nvarchar").IsOptional().HasMaxLength(20);
            Property(x => x.Parity).HasColumnName(@"Parity").HasColumnType("int").IsOptional();
            Property(x => x.FilePath).HasColumnName(@"FilePath").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.AuthorID).HasColumnName(@"AuthorID").HasColumnType("int").IsRequired();
            Property(x => x.EditorID).HasColumnName(@"EditorID").HasColumnType("int").IsOptional();
            Property(x => x.WorkstationID).HasColumnName(@"WorkstationID").HasColumnType("int").IsOptional();
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.UID).HasColumnName(@"UID").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.URL).HasColumnName(@"URL").HasColumnType("nvarchar").IsOptional().HasMaxLength(1024);
            Property(x => x.IsAutostartCounting).HasColumnName(@"IsAutostartCounting").HasColumnType("bit").IsRequired();
            Property(x => x.IsSendEndCount).HasColumnName(@"IsSendEndCount").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
