// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_BaseData_ContactPerson
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_BaseData_ContactPerson
    {
        public int id { get; set; } // id (Primary key)
        public string FirstName { get; set; } // FirstName (length: 255)
        public string MiddleName { get; set; } // MiddleName (length: 255)
        public string LastName { get; set; } // LastName (length: 255)
        public string Email { get; set; } // Email (length: 255)
        public string PhoneNumber { get; set; } // PhoneNumber (length: 30)
        public string FaxNumber { get; set; } // FaxNumber (length: 30)
        public int? Type { get; set; } // Type
        public bool IsPreferred { get; set; } // IsPreferred
        public string JobTitle { get; set; } // JobTitle
        public string OtherPhone { get; set; } // OtherPhone (length: 30)
        public System.Guid UID { get; set; } // UID

        public WP_BaseData_ContactPerson()
        {
            IsPreferred = false;
            UID = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
