// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_BaseData_CustomerBankAccount
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_BaseData_CustomerBankAccountConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_BaseData_CustomerBankAccount>
    {
        public WP_BaseData_CustomerBankAccountConfiguration()
            : this("dbo")
        {
        }

        public WP_BaseData_CustomerBankAccountConfiguration(string schema)
        {
            ToTable("WP_BaseData_CustomerBankAccount", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IsDefault).HasColumnName(@"IsDefault").HasColumnType("bit").IsRequired();
            Property(x => x.Purpose).HasColumnName(@"Purpose").HasColumnType("int").IsOptional();
            Property(x => x.CompanyID).HasColumnName(@"CompanyID").HasColumnType("numeric").IsRequired().HasPrecision(15,0);
            Property(x => x.BankAccountID).HasColumnName(@"BankAccountID").HasColumnType("int").IsRequired();
            Property(x => x.MaterialTypeCode).HasColumnName(@"MaterialTypeCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.UID).HasColumnName(@"UID").HasColumnType("uniqueidentifier").IsRequired();
        }
    }

}
// </auto-generated>
