// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_Billing_InvoiceLine
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_Billing_InvoiceLine
    {
        public int id { get; set; } // id (Primary key)
        public int Quantity { get; set; } // Quantity
        public decimal Value { get; set; } // Value
        public int Sequence { get; set; } // Sequence
        public int InvoiceID { get; set; } // InvoiceID
        public int InvoiceConfigurationLineID { get; set; } // InvoiceConfigurationLineID

        public WP_Billing_InvoiceLine()
        {
            Quantity = 0;
            Value = 0m;
        }
    }

}
// </auto-generated>
