// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_BaseData_ContactDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_BaseData_ContactDetailConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_BaseData_ContactDetail>
    {
        public WP_BaseData_ContactDetailConfiguration()
            : this("dbo")
        {
        }

        public WP_BaseData_ContactDetailConfiguration(string schema)
        {
            ToTable("WP_BaseData_ContactDetails", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Type).HasColumnName(@"Type").HasColumnType("int").IsOptional();
            Property(x => x.FullName).HasColumnName(@"FullName").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Phone).HasColumnName(@"Phone").HasColumnType("nvarchar").IsOptional().HasMaxLength(30);
            Property(x => x.MobilePhone).HasColumnName(@"MobilePhone").HasColumnType("nvarchar").IsOptional().HasMaxLength(30);
            Property(x => x.OtherPhone).HasColumnName(@"OtherPhone").HasColumnType("nvarchar").IsOptional().HasMaxLength(30);
            Property(x => x.Email).HasColumnName(@"Email").HasColumnType("nvarchar").IsOptional().HasMaxLength(80);
            Property(x => x.Fax).HasColumnName(@"Fax").HasColumnType("nvarchar").IsOptional().HasMaxLength(30);
            Property(x => x.Object_id).HasColumnName(@"Object_id").HasColumnType("int").IsRequired();
            Property(x => x.ObjectClass_id).HasColumnName(@"ObjectClass_id").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
