// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_BagTypeMatchingMaterialType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_BagTypeMatchingMaterialTypeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_BagTypeMatchingMaterialType>
    {
        public WP_BagTypeMatchingMaterialTypeConfiguration()
            : this("dbo")
        {
        }

        public WP_BagTypeMatchingMaterialTypeConfiguration(string schema)
        {
            ToTable("WP_BagTypeMatchingMaterialType", schema);
            HasKey(x => new { x.bgtyp_nr, x.matTypeCode });

            Property(x => x.bgtyp_nr).HasColumnName(@"bgtyp_nr").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.matTypeCode).HasColumnName(@"matTypeCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(16).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UID).HasColumnName(@"UID").HasColumnType("uniqueidentifier").IsRequired();
        }
    }

}
// </auto-generated>
