// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_Billing_Invoice
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_Billing_Invoice
    {
        public int id { get; set; } // id (Primary key)
        public string Number { get; set; } // Number (length: 32)
        public int Status { get; set; } // Status
        public System.DateTime DateFrom { get; set; } // DateFrom
        public System.DateTime DateTo { get; set; } // DateTo
        public System.DateTime DateCreated { get; set; } // DateCreated
        public System.DateTime DateUpdated { get; set; } // DateUpdated
        public int AuthorID { get; set; } // AuthorID
        public int EditorID { get; set; } // EditorID

        public WP_Billing_Invoice()
        {
            Status = 1;
            DateCreated = System.DateTime.Now;
            DateUpdated = System.DateTime.Now;
        }
    }

}
// </auto-generated>
