// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_BaseData_DayClosureHistory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_BaseData_DayClosureHistoryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_BaseData_DayClosureHistory>
    {
        public WP_BaseData_DayClosureHistoryConfiguration()
            : this("dbo")
        {
        }

        public WP_BaseData_DayClosureHistoryConfiguration(string schema)
        {
            ToTable("WP_BaseData_DayClosureHistory", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DateCreated).HasColumnName(@"DateCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.Result).HasColumnName(@"Result").HasColumnType("int").IsRequired();
            Property(x => x.Message).HasColumnName(@"Message").HasColumnType("nvarchar(max)").IsRequired();
            Property(x => x.SiteID).HasColumnName(@"SiteID").HasColumnType("int").IsRequired();
            Property(x => x.AuthorID).HasColumnName(@"AuthorID").HasColumnType("int").IsRequired();
            Property(x => x.WorkstationID).HasColumnName(@"WorkstationID").HasColumnType("int").IsRequired();
            Property(x => x.UID).HasColumnName(@"UID").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.Indicator).HasColumnName(@"Indicator").HasColumnType("int").IsOptional();
            Property(x => x.StockOwnerID).HasColumnName(@"StockOwnerID").HasColumnType("int").IsOptional();
            Property(x => x.Process).HasColumnName(@"Process").HasColumnType("int").IsRequired();
            Property(x => x.CurrentTransactionDate).HasColumnName(@"CurrentTransactionDate").HasColumnType("datetime").IsOptional();
            Property(x => x.NextTransactionDate).HasColumnName(@"NextTransactionDate").HasColumnType("datetime").IsOptional();
            Property(x => x.IterationNumber).HasColumnName(@"IterationNumber").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
