// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_BaseData_Process
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_BaseData_Process
    {
        public int id { get; set; } // id (Primary key)
        public int Category { get; set; } // Category
        public int Name { get; set; } // Name
        public bool IsReasonCodeAllowed { get; set; } // IsReasonCodeAllowed

        public WP_BaseData_Process()
        {
            IsReasonCodeAllowed = true;
        }
    }

}
// </auto-generated>
