// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_BaseData_AlarmCodeLocationLink
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_BaseData_AlarmCodeLocationLinkConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_BaseData_AlarmCodeLocationLink>
    {
        public WP_BaseData_AlarmCodeLocationLinkConfiguration()
            : this("dbo")
        {
        }

        public WP_BaseData_AlarmCodeLocationLinkConfiguration(string schema)
        {
            ToTable("WP_BaseData_AlarmCodeLocationLink", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.AlarmCode).HasColumnName(@"AlarmCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(30);
            Property(x => x.LocationID).HasColumnName(@"LocationID").HasColumnType("numeric").IsRequired().HasPrecision(15,0);
        }
    }

}
// </auto-generated>
