// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_BaseData_PLCCurrency
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_BaseData_PLCCurrencyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_BaseData_PLCCurrency>
    {
        public WP_BaseData_PLCCurrencyConfiguration()
            : this("dbo")
        {
        }

        public WP_BaseData_PLCCurrencyConfiguration(string schema)
        {
            ToTable("WP_BaseData_PLCCurrency", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PackNumber).HasColumnName(@"PackNumber").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.ActionDate).HasColumnName(@"ActionDate").HasColumnType("datetime").IsRequired();
            Property(x => x.CurrencyCode).HasColumnName(@"CurrencyCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(30);
            Property(x => x.Value).HasColumnName(@"Value").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
        }
    }

}
// </auto-generated>
