// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_Billing_InvoiceConfigurationLineContractedJobLink
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_Billing_InvoiceConfigurationLineContractedJobLinkConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_Billing_InvoiceConfigurationLineContractedJobLink>
    {
        public WP_Billing_InvoiceConfigurationLineContractedJobLinkConfiguration()
            : this("dbo")
        {
        }

        public WP_Billing_InvoiceConfigurationLineContractedJobLinkConfiguration(string schema)
        {
            ToTable("WP_Billing_InvoiceConfigurationLineContractedJobLink", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.InvoiceConfigurationLineID).HasColumnName(@"InvoiceConfigurationLineID").HasColumnType("int").IsRequired();
            Property(x => x.ContractedJobCode).HasColumnName(@"ContractedJobCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(8);
        }
    }

}
// </auto-generated>
