// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CashCenter_SiteSetting_Barcode_Format
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CashCenter_SiteSetting_Barcode_Format
    {
        public int id { get; set; } // id (Primary key)
        public string Prefix { get; set; } // Prefix (length: 30)
        public int? Length { get; set; } // Length
        public int CashCenterSiteSettingID { get; set; } // CashCenterSiteSettingID
        public decimal? LocationToID { get; set; } // LocationToID
        public System.Guid UID { get; set; } // UID

        public WP_CashCenter_SiteSetting_Barcode_Format()
        {
            UID = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
