// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_Contracts_ContractLine
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_Contracts_ContractLineConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_Contracts_ContractLine>
    {
        public WP_Contracts_ContractLineConfiguration()
            : this("dbo")
        {
        }

        public WP_Contracts_ContractLineConfiguration(string schema)
        {
            ToTable("WP_Contracts_ContractLine", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IsLatestRevision).HasColumnName(@"IsLatestRevision").HasColumnType("bit").IsRequired();
            Property(x => x.RevisionNumber).HasColumnName(@"RevisionNumber").HasColumnType("int").IsOptional();
            Property(x => x.RevisionDate).HasColumnName(@"RevisionDate").HasColumnType("datetime").IsOptional();
            Property(x => x.ReplacedRevisionNumber).HasColumnName(@"ReplacedRevisionNumber").HasColumnType("int").IsOptional();
            Property(x => x.ReplacedRevisionDate).HasColumnName(@"ReplacedRevisionDate").HasColumnType("datetime").IsOptional();
            Property(x => x.Comments).HasColumnName(@"Comments").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Author_id).HasColumnName(@"Author_id").HasColumnType("int").IsOptional();
            Property(x => x.ServicePriceMethod).HasColumnName(@"ServicePriceMethod").HasColumnType("int").IsRequired();
            Property(x => x.ServicePriceOrderLine).HasColumnName(@"ServicePriceOrderLine").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.ServicePricePeriod).HasColumnName(@"ServicePricePeriod").HasColumnType("decimal").IsOptional().HasPrecision(18,2);
            Property(x => x.ServicePeriodNumber).HasColumnName(@"ServicePeriodNumber").HasColumnType("int").IsRequired();
            Property(x => x.ServicePeriodUnits).HasColumnName(@"ServicePeriodUnits").HasColumnType("int").IsRequired();
            Property(x => x.Contract_id).HasColumnName(@"Contract_id").HasColumnType("int").IsRequired();
            Property(x => x.ServiceType_id).HasColumnName(@"ServiceType_id").HasColumnType("int").IsOptional();
            Property(x => x.LocationType_code).HasColumnName(@"LocationType_code").HasColumnType("nvarchar").IsOptional().HasMaxLength(16);
            Property(x => x.RegionContracted_id).HasColumnName(@"RegionContracted_id").HasColumnType("numeric").IsOptional().HasPrecision(15,0);
            Property(x => x.RegionCollect_id).HasColumnName(@"RegionCollect_id").HasColumnType("numeric").IsOptional().HasPrecision(15,0);
            Property(x => x.RegionOnward_id).HasColumnName(@"RegionOnward_id").HasColumnType("numeric").IsOptional().HasPrecision(15,0);
            Property(x => x.LocationContracted_id).HasColumnName(@"LocationContracted_id").HasColumnType("numeric").IsOptional().HasPrecision(15,0);
            Property(x => x.LocationCollect_id).HasColumnName(@"LocationCollect_id").HasColumnType("numeric").IsOptional().HasPrecision(15,0);
            Property(x => x.LocationOnward_id).HasColumnName(@"LocationOnward_id").HasColumnType("numeric").IsOptional().HasPrecision(15,0);
            Property(x => x.LatestRevision_id).HasColumnName(@"LatestRevision_id").HasColumnType("int").IsOptional();
            Property(x => x.Debtor_id).HasColumnName(@"Debtor_id").HasColumnType("numeric").IsOptional().HasPrecision(15,0);
            Property(x => x.BankAccount_id).HasColumnName(@"BankAccount_id").HasColumnType("int").IsOptional();
            Property(x => x.GroupServicePriceOrderLine).HasColumnName(@"GroupServicePriceOrderLine").HasColumnType("decimal").IsOptional().HasPrecision(18,2);
            Property(x => x.UID).HasColumnName(@"UID").HasColumnType("uniqueidentifier").IsRequired();
        }
    }

}
// </auto-generated>
