// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CashCenter_MovementType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CashCenter_MovementTypeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_CashCenter_MovementType>
    {
        public WP_CashCenter_MovementTypeConfiguration()
            : this("dbo")
        {
        }

        public WP_CashCenter_MovementTypeConfiguration(string schema)
        {
            ToTable("WP_CashCenter_MovementType", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.UnsealingUponDelivery).HasColumnName(@"UnsealingUponDelivery").HasColumnType("bit").IsRequired();
            Property(x => x.CountingUponDelivery).HasColumnName(@"CountingUponDelivery").HasColumnType("bit").IsRequired();
            Property(x => x.DateCreated).HasColumnName(@"DateCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.DateUpdated).HasColumnName(@"DateUpdated").HasColumnType("datetime").IsOptional();
            Property(x => x.BagTypeID).HasColumnName(@"BagTypeID").HasColumnType("int").IsOptional();
            Property(x => x.ActualStockLocationTypeID).HasColumnName(@"ActualStockLocationTypeID").HasColumnType("int").IsRequired();
            Property(x => x.DestinationStockLocationTypeID).HasColumnName(@"DestinationStockLocationTypeID").HasColumnType("int").IsOptional();
            Property(x => x.SiteID).HasColumnName(@"SiteID").HasColumnType("int").IsRequired();
            Property(x => x.AuthorID).HasColumnName(@"AuthorID").HasColumnType("int").IsRequired();
            Property(x => x.EditorID).HasColumnName(@"EditorID").HasColumnType("int").IsOptional();
            Property(x => x.TransferOfLiabilityReport).HasColumnName(@"TransferOfLiabilityReport").HasColumnType("bit").IsRequired();
            Property(x => x.UID).HasColumnName(@"UID").HasColumnType("uniqueidentifier").IsRequired();
        }
    }

}
// </auto-generated>
