// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CashCenter_ClieopInterfaceTransactionsLog
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CashCenter_ClieopInterfaceTransactionsLogConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_CashCenter_ClieopInterfaceTransactionsLog>
    {
        public WP_CashCenter_ClieopInterfaceTransactionsLogConfiguration()
            : this("dbo")
        {
        }

        public WP_CashCenter_ClieopInterfaceTransactionsLogConfiguration(string schema)
        {
            ToTable("WP_CashCenter_ClieopInterfaceTransactionsLog", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ResultingFileName).HasColumnName(@"ResultingFileName").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.ATMTransactionID).HasColumnName(@"ATMTransactionID").HasColumnType("int").IsRequired();
            Property(x => x.ExportType).HasColumnName(@"ExportType").HasColumnType("int").IsRequired();
            Property(x => x.DateCreated).HasColumnName(@"DateCreated").HasColumnType("datetime").IsRequired();
        }
    }

}
// </auto-generated>
