// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CM_OptimizationSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CM_OptimizationSetting
    {
        public int id { get; set; } // id (Primary key)
        public decimal CorrectionFactor { get; set; } // CorrectionFactor
        public int WeeksNumber { get; set; } // WeeksNumber
        public decimal DeterminationMinimum { get; set; } // DeterminationMinimum
        public double ExecutionTime { get; set; } // ExecutionTime
        public bool IsBusy { get; set; } // IsBusy
        public bool EnableOrderCreation { get; set; } // EnableOrderCreation
        public bool ForceOrderConfirmation { get; set; } // ForceOrderConfirmation
        public int? AbnormalUsageGreenValue { get; set; } // AbnormalUsageGreenValue
        public int? AbnormalUsageOrangeValue { get; set; } // AbnormalUsageOrangeValue
        public int FallbackPeriod { get; set; } // FallbackPeriod
        public System.DateTime? LastOptimizationDate { get; set; } // LastOptimizationDate
        public bool IsFillDaily { get; set; } // IsFillDaily
        public int AverageTurnoverPeriod { get; set; } // AverageTurnoverPeriod
        public bool TrustOrdersInProgress { get; set; } // TrustOrdersInProgress
        public int ForecastPeriod { get; set; } // ForecastPeriod
        public decimal? CompanyID { get; set; } // CompanyID
        public int? MachineTypeID { get; set; } // MachineTypeID
        public bool RoundOrderQuantityDown { get; set; } // RoundOrderQuantityDown
        public decimal? LocationID { get; set; } // LocationID
        public decimal InterestRate { get; set; } // InterestRate

        public WP_CM_OptimizationSetting()
        {
            IsBusy = false;
            EnableOrderCreation = true;
            ForceOrderConfirmation = true;
            FallbackPeriod = 0;
            IsFillDaily = false;
            AverageTurnoverPeriod = 0;
            TrustOrdersInProgress = true;
            ForecastPeriod = 30;
            RoundOrderQuantityDown = false;
            InterestRate = 0m;
        }
    }

}
// </auto-generated>
