// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CashCenter_StockLocation
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CashCenter_StockLocationConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_CashCenter_StockLocation>
    {
        public WP_CashCenter_StockLocationConfiguration()
            : this("dbo")
        {
        }

        public WP_CashCenter_StockLocationConfiguration(string schema)
        {
            ToTable("WP_CashCenter_StockLocation", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Number).HasColumnName(@"Number").HasColumnType("nvarchar").IsRequired().HasMaxLength(30);
            Property(x => x.ReferenceNumber).HasColumnName(@"ReferenceNumber").HasColumnType("nvarchar").IsOptional().HasMaxLength(30);
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("int").IsRequired();
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.DateCreated).HasColumnName(@"DateCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.DateUpdated).HasColumnName(@"DateUpdated").HasColumnType("datetime").IsOptional();
            Property(x => x.ParentStockLocation_id).HasColumnName(@"ParentStockLocation_id").HasColumnType("int").IsOptional();
            Property(x => x.StockOwner_id).HasColumnName(@"StockOwner_id").HasColumnType("int").IsOptional();
            Property(x => x.Site_id).HasColumnName(@"Site_id").HasColumnType("int").IsRequired();
            Property(x => x.Location_id).HasColumnName(@"Location_id").HasColumnType("numeric").IsOptional().HasPrecision(15,0);
            Property(x => x.Workstation_id).HasColumnName(@"Workstation_id").HasColumnType("int").IsOptional();
            Property(x => x.Author_id).HasColumnName(@"Author_id").HasColumnType("int").IsOptional();
            Property(x => x.Editor_id).HasColumnName(@"Editor_id").HasColumnType("int").IsOptional();
            Property(x => x.StockLocationTypeID).HasColumnName(@"StockLocationTypeID").HasColumnType("int").IsRequired();
            Property(x => x.UID).HasColumnName(@"UID").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.DefaultStockOwnerID).HasColumnName(@"DefaultStockOwnerID").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
