// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CM_DailyMachineRecord
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CM_DailyMachineRecordConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_CM_DailyMachineRecord>
    {
        public WP_CM_DailyMachineRecordConfiguration()
            : this("dbo")
        {
        }

        public WP_CM_DailyMachineRecordConfiguration(string schema)
        {
            ToTable("WP_CM_DailyMachineRecord", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.StockDate).HasColumnName(@"StockDate").HasColumnType("datetime").IsRequired();
            Property(x => x.QuantityDayTurnover).HasColumnName(@"QuantityDayTurnover").HasColumnType("int").IsRequired();
            Property(x => x.Machine_id).HasColumnName(@"Machine_id").HasColumnType("int").IsRequired();
            Property(x => x.ValueDayTurnover).HasColumnName(@"ValueDayTurnover").HasColumnType("decimal").IsRequired().HasPrecision(26,8);
            Property(x => x.StockQuantity).HasColumnName(@"StockQuantity").HasColumnType("int").IsOptional();
            Property(x => x.StockValue).HasColumnName(@"StockValue").HasColumnType("decimal").IsRequired().HasPrecision(26,8);
            Property(x => x.StockExpirationDate).HasColumnName(@"StockExpirationDate").HasColumnType("datetime").IsOptional();
            Property(x => x.FirstServiceDate).HasColumnName(@"FirstServiceDate").HasColumnType("datetime").IsOptional();
            Property(x => x.NextServiceDate).HasColumnName(@"NextServiceDate").HasColumnType("datetime").IsOptional();
        }
    }

}
// </auto-generated>
