// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CM_SiebelSyncSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CM_SiebelSyncSettingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_CM_SiebelSyncSetting>
    {
        public WP_CM_SiebelSyncSettingConfiguration()
            : this("dbo")
        {
        }

        public WP_CM_SiebelSyncSettingConfiguration(string schema)
        {
            ToTable("WP_CM_SiebelSyncSettings", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.FolderToGetFiles).HasColumnName(@"FolderToGetFiles").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.FolderToPutImportFiles).HasColumnName(@"FolderToPutImportFiles").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.FolderToPutFeedingsFiles).HasColumnName(@"FolderToPutFeedingsFiles").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
        }
    }

}
// </auto-generated>
