// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_Contracts_ScheduleLine
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_Contracts_ScheduleLine
    {
        public int id { get; set; } // id (Primary key)
        public bool IsLatestRevision { get; set; } // IsLatestRevision
        public int? RevisionNumber { get; set; } // RevisionNumber
        public System.DateTime? RevisionDate { get; set; } // RevisionDate
        public int? ReplacedRevisionNumber { get; set; } // ReplacedRevisionNumber
        public System.DateTime? ReplacedRevisionDate { get; set; } // ReplacedRevisionDate
        public string Comments { get; set; } // Comments
        public int? Author_id { get; set; } // Author_id
        public int? WeekdayName { get; set; } // WeekdayName
        public int? WeekdayNumberInMonth { get; set; } // WeekdayNumberInMonth
        public int OrderType { get; set; } // OrderType
        public int PeriodNumber { get; set; } // PeriodNumber
        public int PeriodUnits { get; set; } // PeriodUnits
        public int SurchargePercentage { get; set; } // SurchargePercentage
        public decimal SurchargeValue { get; set; } // SurchargeValue
        public int CancellationPercentage { get; set; } // CancellationPercentage
        public decimal CancellationValue { get; set; } // CancellationValue
        public int? MasterRoute_id { get; set; } // MasterRoute_id
        public int? LatestRevision_id { get; set; } // LatestRevision_id
        public int ScheduleSetting_id { get; set; } // ScheduleSetting_id
        public System.Guid UID { get; set; } // UID

        public WP_Contracts_ScheduleLine()
        {
            IsLatestRevision = false;
            OrderType = 2;
            PeriodNumber = 1;
            PeriodUnits = 1;
            SurchargePercentage = 100;
            SurchargeValue = 0m;
            CancellationPercentage = 100;
            CancellationValue = 0m;
            ScheduleSetting_id = -1;
            UID = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
