// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CashCenter_SiteSetting_MaterialType_Link
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CashCenter_SiteSetting_MaterialType_Link
    {
        public int Id { get; set; } // Id (Primary key)
        public string MaterialTypeCode { get; set; } // MaterialTypeCode (length: 10)
        public int CashCenterSiteSettingID { get; set; } // CashCenterSiteSettingID
        public System.Guid UID { get; set; } // UID

        public WP_CashCenter_SiteSetting_MaterialType_Link()
        {
            UID = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
