// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CashCenter_SiteSettingStockOwner
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CashCenter_SiteSettingStockOwnerConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_CashCenter_SiteSettingStockOwner>
    {
        public WP_CashCenter_SiteSettingStockOwnerConfiguration()
            : this("dbo")
        {
        }

        public WP_CashCenter_SiteSettingStockOwnerConfiguration(string schema)
        {
            ToTable("WP_CashCenter_SiteSettingStockOwner", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DayClosureTime).HasColumnName(@"DayClosureTime").HasColumnType("time").IsRequired();
            Property(x => x.CashCenterSiteSettingID).HasColumnName(@"CashCenterSiteSettingID").HasColumnType("int").IsRequired();
            Property(x => x.StockOwnerID).HasColumnName(@"StockOwnerID").HasColumnType("int").IsOptional();
            Property(x => x.UID).HasColumnName(@"UID").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.Process).HasColumnName(@"Process").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
