// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CM_SiebelSyncSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CM_SiebelSyncSetting
    {
        public int id { get; set; } // id (Primary key)
        public string FolderToGetFiles { get; set; } // FolderToGetFiles (length: 255)
        public string FolderToPutImportFiles { get; set; } // FolderToPutImportFiles (length: 255)
        public string FolderToPutFeedingsFiles { get; set; } // FolderToPutFeedingsFiles (length: 255)
    }

}
// </auto-generated>
