// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_Contracts_ContractedJobLink
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_Contracts_ContractedJobLink
    {
        public int id { get; set; } // id (Primary key)
        public bool IsLatestRevision { get; set; } // IsLatestRevision
        public int? RevisionNumber { get; set; } // RevisionNumber
        public System.DateTime? RevisionDate { get; set; } // RevisionDate
        public int? ReplacedRevisionNumber { get; set; } // ReplacedRevisionNumber
        public System.DateTime? ReplacedRevisionDate { get; set; } // ReplacedRevisionDate
        public string Comments { get; set; } // Comments
        public int? Author_id { get; set; } // Author_id
        public decimal Price { get; set; } // Price
        public int PriceItem { get; set; } // PriceItem
        public int PriceApplication { get; set; } // PriceApplication
        public int? PriceItemsFrom { get; set; } // PriceItemsFrom
        public int? PriceItemsTo { get; set; } // PriceItemsTo
        public bool IsWithOtherJobs { get; set; } // IsWithOtherJobs
        public bool IsMainLocation { get; set; } // IsMainLocation
        public bool IsApplySurcharges { get; set; } // IsApplySurcharges
        public int ContractLine_id { get; set; } // ContractLine_id
        public string ServicingCode_code { get; set; } // ServicingCode_code (length: 8)
        public int PackagesFilterType { get; set; } // PackagesFilterType
        public int? LatestRevision_id { get; set; } // LatestRevision_id
        public System.Guid UID { get; set; } // UID

        public WP_Contracts_ContractedJobLink()
        {
            IsLatestRevision = true;
            Price = 0m;
            PriceItem = 0;
            PriceApplication = 0;
            IsWithOtherJobs = false;
            IsMainLocation = false;
            IsApplySurcharges = true;
            PackagesFilterType = 0;
            UID = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
