// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CashCenter_SiteStockHistory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CashCenter_SiteStockHistory
    {
        public int id { get; set; } // id (Primary key)
        public System.DateTime StockDate { get; set; } // StockDate
        public int StockType { get; set; } // StockType
        public bool IsFinalized { get; set; } // IsFinalized
        public System.DateTime DateCreated { get; set; } // DateCreated
        public int? StockLocationID { get; set; } // StockLocationID
        public int StockOwnerID { get; set; } // StockOwnerID
        public string CurrencyID { get; set; } // CurrencyID (length: 3)
        public System.DateTime DateUpdated { get; set; } // DateUpdated
        public System.Guid UID { get; set; } // UID

        public WP_CashCenter_SiteStockHistory()
        {
            IsFinalized = false;
            UID = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
