// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CashCenter_ProcessingRemark
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CashCenter_ProcessingRemark
    {
        public long id { get; set; } // id (Primary key)
        public string Remark { get; set; } // Remark
        public System.DateTime DateCreated { get; set; } // DateCreated
        public long? ObjectID { get; set; } // ObjectID
        public int? ObjectClassID { get; set; } // ObjectClassID
        public int? ProcessingReasonCodeID { get; set; } // ProcessingReasonCodeID
        public int? UserID { get; set; } // UserID
        public int? WorkstationID { get; set; } // WorkstationID
        public int? SecondUserID { get; set; } // SecondUserID
        public System.Guid UID { get; set; } // UID

        public WP_CashCenter_ProcessingRemark()
        {
            UID = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
