// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_Common_LinkedFiles
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_Common_LinkedFileConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_Common_LinkedFile>
    {
        public WP_Common_LinkedFileConfiguration()
            : this("dbo")
        {
        }

        public WP_Common_LinkedFileConfiguration(string schema)
        {
            ToTable("WP_Common_LinkedFiles", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DocumentID).HasColumnName(@"DocumentID").HasColumnType("bigint").IsRequired();
            Property(x => x.ClassDescriptionID).HasColumnName(@"ClassDescriptionID").HasColumnType("int").IsRequired();
            Property(x => x.FileName).HasColumnName(@"FileName").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.FileContent).HasColumnName(@"FileContent").HasColumnType("varbinary(max)").IsRequired();
            Property(x => x.AttachDate).HasColumnName(@"AttachDate").HasColumnType("datetime").IsRequired();
            Property(x => x.FileSize).HasColumnName(@"FileSize").HasColumnType("decimal").IsRequired().HasPrecision(18,3);
            Property(x => x.FileStatus).HasColumnName(@"FileStatus").HasColumnType("int").IsRequired();
            Property(x => x.AuthorID).HasColumnName(@"AuthorID").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
