// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CallManagement_SLAMonitorJobSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CallManagement_SLAMonitorJobSettingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_CallManagement_SLAMonitorJobSetting>
    {
        public WP_CallManagement_SLAMonitorJobSettingConfiguration()
            : this("dbo")
        {
        }

        public WP_CallManagement_SLAMonitorJobSettingConfiguration(string schema)
        {
            ToTable("WP_CallManagement_SLAMonitorJobSettings", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Timeout).HasColumnName(@"Timeout").HasColumnType("int").IsOptional();
            Property(x => x.NotifyOperatorSLAResolveViolation).HasColumnName(@"NotifyOperatorSLAResolveViolation").HasColumnType("bit").IsRequired();
            Property(x => x.NotifyOperatorBeforeSLA).HasColumnName(@"NotifyOperatorBeforeSLA").HasColumnType("bit").IsRequired();
            Property(x => x.BeforeSLATimeout).HasColumnName(@"BeforeSLATimeout").HasColumnType("int").IsOptional();
            Property(x => x.NotifyManagementSLAFixViolation).HasColumnName(@"NotifyManagementSLAFixViolation").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
