// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CashCenter_SiteSettingBagTypeLink
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CashCenter_SiteSettingBagTypeLink
    {
        public int id { get; set; } // id (Primary key)
        public int PrintTransportStickers { get; set; } // PrintTransportStickers
        public int? TransportStickerType { get; set; } // TransportStickerType
        public bool IsDefault { get; set; } // IsDefault
        public int? CashCenterSiteSettingID { get; set; } // CashCenterSiteSettingID
        public int? BagTypeID { get; set; } // BagTypeID
        public string StickerText { get; set; } // StickerText (length: 50)
        public System.Guid UID { get; set; } // UID
        public bool IsShowReference { get; set; } // IsShowReference
        public bool IsShowValue { get; set; } // IsShowValue

        public WP_CashCenter_SiteSettingBagTypeLink()
        {
            IsDefault = false;
            UID = System.Guid.NewGuid();
            IsShowReference = false;
            IsShowValue = false;
        }
    }

}
// </auto-generated>
