// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CashCenter_StockOwner
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CashCenter_StockOwnerConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_CashCenter_StockOwner>
    {
        public WP_CashCenter_StockOwnerConfiguration()
            : this("dbo")
        {
        }

        public WP_CashCenter_StockOwnerConfiguration(string schema)
        {
            ToTable("WP_CashCenter_StockOwner", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ConsignmentTaker).HasColumnName(@"ConsignmentTaker").HasColumnType("bit").IsRequired();
            Property(x => x.MatchingAllowed).HasColumnName(@"MatchingAllowed").HasColumnType("bit").IsRequired();
            Property(x => x.MaximumRecycleStock).HasColumnName(@"MaximumRecycleStock").HasColumnType("numeric").IsOptional().HasPrecision(17,2);
            Property(x => x.MinimumRecycleStock).HasColumnName(@"MinimumRecycleStock").HasColumnType("numeric").IsOptional().HasPrecision(17,2);
            Property(x => x.DateCreated).HasColumnName(@"DateCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.DateUpdated).HasColumnName(@"DateUpdated").HasColumnType("datetime").IsOptional();
            Property(x => x.Customer_id).HasColumnName(@"Customer_id").HasColumnType("numeric").IsRequired().HasPrecision(15,0);
            Property(x => x.Author_id).HasColumnName(@"Author_id").HasColumnType("int").IsRequired();
            Property(x => x.Editor_id).HasColumnName(@"Editor_id").HasColumnType("int").IsOptional();
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.UID).HasColumnName(@"UID").HasColumnType("uniqueidentifier").IsRequired();
        }
    }

}
// </auto-generated>
