// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CM_OfflineTimeHistory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CM_OfflineTimeHistoryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_CM_OfflineTimeHistory>
    {
        public WP_CM_OfflineTimeHistoryConfiguration()
            : this("dbo")
        {
        }

        public WP_CM_OfflineTimeHistoryConfiguration(string schema)
        {
            ToTable("WP_CM_OfflineTimeHistory", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.TimeOffline).HasColumnName(@"TimeOffline").HasColumnType("float").IsRequired();
            Property(x => x.TimeOpen).HasColumnName(@"TimeOpen").HasColumnType("float").IsRequired();
            Property(x => x.Date).HasColumnName(@"Date").HasColumnType("datetime").IsRequired();
            Property(x => x.CategoryID).HasColumnName(@"CategoryID").HasColumnType("int").IsOptional();
            Property(x => x.MachineID).HasColumnName(@"MachineID").HasColumnType("int").IsRequired();
            Property(x => x.TimeCorrection).HasColumnName(@"TimeCorrection").HasColumnType("float").IsOptional();
            Property(x => x.IsTotal).HasColumnName(@"IsTotal").HasColumnType("bit").IsRequired();
            Property(x => x.DateCreated).HasColumnName(@"DateCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.DateUpdated).HasColumnName(@"DateUpdated").HasColumnType("datetime").IsRequired();
            Property(x => x.StatusCodeId).HasColumnName(@"StatusCodeId").HasColumnType("int").IsOptional();
            Property(x => x.Errors).HasColumnName(@"Errors").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
