// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CM_Transaction
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CM_TransactionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_CM_Transaction>
    {
        public WP_CM_TransactionConfiguration()
            : this("dbo")
        {
        }

        public WP_CM_TransactionConfiguration(string schema)
        {
            ToTable("WP_CM_Transaction", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Type).HasColumnName(@"Type").HasColumnType("int").IsOptional();
            Property(x => x.Number).HasColumnName(@"Number").HasColumnType("int").IsOptional();
            Property(x => x.StartDate).HasColumnName(@"StartDate").HasColumnType("datetime").IsOptional();
            Property(x => x.EndDate).HasColumnName(@"EndDate").HasColumnType("datetime").IsOptional();
            Property(x => x.BankNumber).HasColumnName(@"BankNumber").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.AccountNumber).HasColumnName(@"AccountNumber").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Value).HasColumnName(@"Value").HasColumnType("decimal").IsOptional().HasPrecision(18,2);
            Property(x => x.Change).HasColumnName(@"Change").HasColumnType("decimal").IsOptional().HasPrecision(18,2);
            Property(x => x.Fee).HasColumnName(@"Fee").HasColumnType("decimal").IsOptional().HasPrecision(18,2);
            Property(x => x.Weight).HasColumnName(@"Weight").HasColumnType("decimal").IsOptional().HasPrecision(15,5);
            Property(x => x.Quantity).HasColumnName(@"Quantity").HasColumnType("int").IsOptional();
            Property(x => x.PaymentMethod).HasColumnName(@"PaymentMethod").HasColumnType("int").IsOptional();
            Property(x => x.Machine_id).HasColumnName(@"Machine_id").HasColumnType("int").IsOptional();
            Property(x => x.CurrencyCode).HasColumnName(@"CurrencyCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(3);
            Property(x => x.Replenishment).HasColumnName(@"Replenishment").HasColumnType("bit").IsRequired();
            Property(x => x.Bic).HasColumnName(@"Bic").HasColumnType("nvarchar").IsOptional().HasMaxLength(20);
            Property(x => x.SealNumber).HasColumnName(@"SealNumber").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.DateCreated).HasColumnName(@"DateCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.StaffNumber).HasColumnName(@"StaffNumber").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.SecondStaffNumber).HasColumnName(@"SecondStaffNumber").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.IsBackdated).HasColumnName(@"IsBackdated").HasColumnType("bit").IsRequired();
            Property(x => x.IsProcessBackdated).HasColumnName(@"IsProcessBackdated").HasColumnType("bit").IsRequired();
            Property(x => x.IsUseBackdated).HasColumnName(@"IsUseBackdated").HasColumnType("bit").IsRequired();
            Property(x => x.Comment).HasColumnName(@"Comment").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
        }
    }

}
// </auto-generated>
