// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CashCenter_StockPosition
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CashCenter_StockPositionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_CashCenter_StockPosition>
    {
        public WP_CashCenter_StockPositionConfiguration()
            : this("dbo")
        {
        }

        public WP_CashCenter_StockPositionConfiguration(string schema)
        {
            ToTable("WP_CashCenter_StockPosition", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IsVerified).HasColumnName(@"IsVerified").HasColumnType("bit").IsRequired();
            Property(x => x.QualificationType).HasColumnName(@"QualificationType").HasColumnType("int").IsRequired();
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("int").IsRequired();
            Property(x => x.Quantity).HasColumnName(@"Quantity").HasColumnType("int").IsRequired();
            Property(x => x.Value).HasColumnName(@"Value").HasColumnType("numeric").IsRequired().HasPrecision(15,2);
            Property(x => x.Weight).HasColumnName(@"Weight").HasColumnType("numeric").IsRequired().HasPrecision(15,5);
            Property(x => x.DateCreated).HasColumnName(@"DateCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.DateUpdated).HasColumnName(@"DateUpdated").HasColumnType("datetime").IsRequired();
            Property(x => x.Material_id).HasColumnName(@"Material_id").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.Product_id).HasColumnName(@"Product_id").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.StockContainer_id).HasColumnName(@"StockContainer_id").HasColumnType("bigint").IsOptional();
            Property(x => x.StockLocation_id).HasColumnName(@"StockLocation_id").HasColumnType("int").IsOptional();
            Property(x => x.Currency_id).HasColumnName(@"Currency_id").HasColumnType("nvarchar").IsRequired().HasMaxLength(3);
            Property(x => x.IsTotal).HasColumnName(@"IsTotal").HasColumnType("bit").IsRequired();
            Property(x => x.StockOwner_id).HasColumnName(@"StockOwner_id").HasColumnType("int").IsOptional();
            Property(x => x.Author_id).HasColumnName(@"Author_id").HasColumnType("int").IsOptional();
            Property(x => x.Editor_id).HasColumnName(@"Editor_id").HasColumnType("int").IsOptional();
            Property(x => x.UID).HasColumnName(@"UID").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.TransactionDate).HasColumnName(@"TransactionDate").HasColumnType("datetime").IsOptional();
        }
    }

}
// </auto-generated>
