// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CM_ExactCustomerSyncSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CM_ExactCustomerSyncSettingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_CM_ExactCustomerSyncSetting>
    {
        public WP_CM_ExactCustomerSyncSettingConfiguration()
            : this("dbo")
        {
        }

        public WP_CM_ExactCustomerSyncSettingConfiguration(string schema)
        {
            ToTable("WP_CM_ExactCustomerSyncSettings", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CustomerID).HasColumnName(@"CustomerID").HasColumnType("numeric").IsOptional().HasPrecision(15,0);
            Property(x => x.JournalCode).HasColumnName(@"JournalCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.JournalType).HasColumnName(@"JournalType").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.AccountCode).HasColumnName(@"AccountCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.WarehouseCode).HasColumnName(@"WarehouseCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.ItemType).HasColumnName(@"ItemType").HasColumnType("int").IsOptional();
            Property(x => x.ProductOrMaterialID).HasColumnName(@"ProductOrMaterialID").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.ProjectCode).HasColumnName(@"ProjectCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.TransactionLineType).HasColumnName(@"TransactionLineType").HasColumnType("int").IsOptional();
            Property(x => x.MachineType_id).HasColumnName(@"MachineType_id").HasColumnType("int").IsOptional();
            Property(x => x.Replenishment).HasColumnName(@"Replenishment").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
