// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CM_EOMCommonSyncSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CM_EOMCommonSyncSetting
    {
        public int id { get; set; } // id (Primary key)
        public string FolderToGetFiles { get; set; } // FolderToGetFiles (length: 255)
        public string FileKind { get; set; } // FileKind (length: 4)
        public string FolderToGetBoekBestandFiles { get; set; } // FolderToGetBoekBestandFiles (length: 255)
        public int ResidualCode { get; set; } // ResidualCode
        public int RejectsCode { get; set; } // RejectsCode
        public int RetractsCode { get; set; } // RetractsCode
        public string FolderToGetFallbackOrdersFiles { get; set; } // FolderToGetFallbackOrdersFiles (length: 255)
        public string FallbackOrdersFileKind { get; set; } // FallbackOrdersFileKind (length: 4)

        public WP_CM_EOMCommonSyncSetting()
        {
            ResidualCode = 0;
            RejectsCode = 1;
            RetractsCode = 2;
        }
    }

}
// </auto-generated>
