// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CashCenter_CountResult
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CashCenter_CountResult
    {
        public long id { get; set; } // id (Primary key)
        public System.DateTime DateCreated { get; set; } // DateCreated
        public System.DateTime DateUpdated { get; set; } // DateUpdated
        public System.DateTime DateCounted { get; set; } // DateCounted
        public string MachineNumber { get; set; } // MachineNumber (length: 30)
        public long? StockContainerID { get; set; } // StockContainerID
        public int? DailyHeaderCardID { get; set; } // DailyHeaderCardID
        public int? WorkstationID { get; set; } // WorkstationID
        public int? OperatorID { get; set; } // OperatorID
        public string SequenceNumber { get; set; } // SequenceNumber (length: 30)
        public int? StockOwnerID { get; set; } // StockOwnerID
        public System.Guid UID { get; set; } // UID
        public System.DateTime DateOccurred { get; set; } // DateOccurred

        public WP_CashCenter_CountResult()
        {
            UID = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
