// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CashCenter_ProcessingReasonCode
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CashCenter_ProcessingReasonCode
    {
        public int id { get; set; } // id (Primary key)
        public string Name { get; set; } // Name (length: 255)
        public string Description { get; set; } // Description
        public bool IsAnomaly { get; set; } // IsAnomaly
        public int? ProcessName { get; set; } // ProcessName
        public System.Guid UID { get; set; } // UID
        public bool IsMisscan { get; set; } // IsMisscan
        public int ProcessCategory { get; set; } // ProcessCategory
        public int Responsible { get; set; } // Responsible
        public int? TransportOrderAction { get; set; } // TransportOrderAction
        public int? PDACode { get; set; } // PDACode
        public System.DateTime DateCreated { get; set; } // DateCreated
        public System.DateTime DateUpdated { get; set; } // DateUpdated
        public int? AuthorId { get; set; } // AuthorId
        public int? EditorId { get; set; } // EditorId

        public WP_CashCenter_ProcessingReasonCode()
        {
            UID = System.Guid.NewGuid();
            IsMisscan = false;
            ProcessCategory = 0;
            Responsible = 0;
            DateCreated = System.DateTime.Now;
            DateUpdated = System.DateTime.Now;
        }
    }

}
// </auto-generated>
