// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CM_CashPointInterfaceSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CM_CashPointInterfaceSettingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_CM_CashPointInterfaceSetting>
    {
        public WP_CM_CashPointInterfaceSettingConfiguration()
            : this("dbo")
        {
        }

        public WP_CM_CashPointInterfaceSettingConfiguration(string schema)
        {
            ToTable("WP_CM_CashPointInterfaceSettings", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IsBusy).HasColumnName(@"IsBusy").HasColumnType("bit").IsOptional();
            Property(x => x.IsExport).HasColumnName(@"IsExport").HasColumnType("bit").IsOptional();
            Property(x => x.ExportDayOfMonth).HasColumnName(@"ExportDayOfMonth").HasColumnType("int").IsOptional();
            Property(x => x.ExportTime).HasColumnName(@"ExportTime").HasColumnType("float").IsOptional();
            Property(x => x.FilePrefix).HasColumnName(@"FilePrefix").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.LocationNamesSubstrings).HasColumnName(@"LocationNamesSubstrings").HasColumnType("nvarchar").IsOptional().HasMaxLength(1000);
            Property(x => x.ExportFolder).HasColumnName(@"ExportFolder").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.VersionNumber).HasColumnName(@"VersionNumber").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
