// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CashCenter_PackingLine
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CashCenter_PackingLine
    {
        public long id { get; set; } // id (Primary key)
        public long Number { get; set; } // Number
        public string Description { get; set; } // Description (length: 50)
        public System.DateTime DateFrom { get; set; } // DateFrom
        public System.DateTime? DateTo { get; set; } // DateTo
        public int PackingMode { get; set; } // PackingMode
        public System.DateTime DateCreated { get; set; } // DateCreated
        public System.DateTime DateUpdated { get; set; } // DateUpdated
        public int AuthorId { get; set; } // AuthorId
        public int? EditorId { get; set; } // EditorId
        public int PackingType { get; set; } // PackingType
        public System.Guid UID { get; set; } // UID

        public WP_CashCenter_PackingLine()
        {
            PackingType = 1;
            UID = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
