// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CM_StatusMessage
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CM_StatusMessage
    {
        public int id { get; set; } // id (Primary key)
        public System.DateTime? Date { get; set; } // Date
        public int? MessageNumber { get; set; } // MessageNumber
        public int? StatusCode_id { get; set; } // StatusCode_id
        public string SubstatusCode { get; set; } // SubstatusCode (length: 255)
        public string Description { get; set; } // Description
        public string Version { get; set; } // Version (length: 255)
        public string DeviceName { get; set; } // DeviceName (length: 255)
        public string DeviceID { get; set; } // DeviceID (length: 255)
        public string DeviceType { get; set; } // DeviceType (length: 255)
        public string DeviceVersion { get; set; } // DeviceVersion (length: 255)
        public string Manufacturer { get; set; } // Manufacturer (length: 255)
        public int? Category { get; set; } // Category
        public string OrderId { get; set; } // OrderId (length: 20)
        public int Resolved { get; set; } // Resolved
        public System.DateTime? ResolveTime { get; set; } // ResolveTime
        public System.DateTime? DateResolved { get; set; } // DateResolved
        public int? Machine_id { get; set; } // Machine_id
        public double? TimeOffline { get; set; } // TimeOffline
        public bool? IsCallGenerated { get; set; } // IsCallGenerated
        public System.DateTime DateUpdated { get; set; } // DateUpdated

        public WP_CM_StatusMessage()
        {
            Resolved = 0;
        }
    }

}
// </auto-generated>
