// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CashCenter_CountResultLine
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CashCenter_CountResultLine
    {
        public long id { get; set; } // id
        public int QualificationType { get; set; } // QualificationType
        public decimal Denomination { get; set; } // Denomination
        public string MaterialTypeCode { get; set; } // MaterialTypeCode (length: 10)
        public long Quantity { get; set; } // Quantity
        public decimal Value { get; set; } // Value
        public decimal Weight { get; set; } // Weight
        public long CountResultID { get; set; } // CountResultID
        public string MaterialID { get; set; } // MaterialID (length: 10)
        public string CurrencyID { get; set; } // CurrencyID (length: 3)
        public System.Guid UID { get; set; } // UID (Primary key via unique index idx_WP_CashCenter_CountResultLine_UID)
        public System.DateTime? TransactionDate { get; set; } // TransactionDate
        public int? ProductID { get; set; } // ProductID

        public WP_CashCenter_CountResultLine()
        {
            Quantity = 0;
            Value = 0m;
            Weight = 0m;
            UID = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
