// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CashPoint_InsuranceSetting
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CashPoint_InsuranceSetting
    {
        public int id { get; set; } // id (Primary key)
        public decimal InsuranceLimit { get; set; } // InsuranceLimit
        public bool IsDefault { get; set; } // IsDefault
        public byte Level { get; set; } // Level
        public System.DateTime DateCreated { get; set; } // DateCreated
        public System.DateTime DateUpdated { get; set; } // DateUpdated
        public int? CompanyId { get; set; } // CompanyId
        public int? CashPointModelId { get; set; } // CashPointModelId
        public int? CashPointId { get; set; } // CashPointId
        public int? ParentInsuranceSettingId { get; set; } // ParentInsuranceSettingId
        public int? AuthorId { get; set; } // AuthorId
        public int? EditorId { get; set; } // EditorId
    }

}
// </auto-generated>
