// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CM_CashOutTimeHistory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CM_CashOutTimeHistoryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_CM_CashOutTimeHistory>
    {
        public WP_CM_CashOutTimeHistoryConfiguration()
            : this("dbo")
        {
        }

        public WP_CM_CashOutTimeHistoryConfiguration(string schema)
        {
            ToTable("WP_CM_CashOutTimeHistory", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.TimeCollectOneRed).HasColumnName(@"TimeCollectOneRed").HasColumnType("float").IsRequired();
            Property(x => x.TimeCollectAllRed).HasColumnName(@"TimeCollectAllRed").HasColumnType("float").IsRequired();
            Property(x => x.TimeIssueOneRed).HasColumnName(@"TimeIssueOneRed").HasColumnType("float").IsRequired();
            Property(x => x.TimeIssueAllRed).HasColumnName(@"TimeIssueAllRed").HasColumnType("float").IsRequired();
            Property(x => x.TimeIssueOneMinimum).HasColumnName(@"TimeIssueOneMinimum").HasColumnType("float").IsRequired();
            Property(x => x.TimeIssueAllMinimum).HasColumnName(@"TimeIssueAllMinimum").HasColumnType("float").IsRequired();
            Property(x => x.MinimumNotes).HasColumnName(@"MinimumNotes").HasColumnType("int").IsRequired();
            Property(x => x.MinimumCoins).HasColumnName(@"MinimumCoins").HasColumnType("int").IsRequired();
            Property(x => x.Date).HasColumnName(@"Date").HasColumnType("datetime").IsRequired();
            Property(x => x.MachineID).HasColumnName(@"MachineID").HasColumnType("int").IsRequired();
            Property(x => x.TimeRecycleCollectOneRed).HasColumnName(@"TimeRecycleCollectOneRed").HasColumnType("float").IsRequired();
            Property(x => x.TimeRecycleCollectAllRed).HasColumnName(@"TimeRecycleCollectAllRed").HasColumnType("float").IsRequired();
            Property(x => x.TimeRecycleIssueOneRed).HasColumnName(@"TimeRecycleIssueOneRed").HasColumnType("float").IsRequired();
            Property(x => x.TimeRecycleIssueAllRed).HasColumnName(@"TimeRecycleIssueAllRed").HasColumnType("float").IsRequired();
            Property(x => x.TimeRecycleIssueOneMinimum).HasColumnName(@"TimeRecycleIssueOneMinimum").HasColumnType("float").IsRequired();
            Property(x => x.TimeRecycleIssueAllMinimum).HasColumnName(@"TimeRecycleIssueAllMinimum").HasColumnType("float").IsRequired();
        }
    }

}
// </auto-generated>
