// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_CashCenter_BarcodeScanHistory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_CashCenter_BarcodeScanHistory
    {
        public int id { get; set; } // id (Primary key)
        public string BarcodeNumber { get; set; } // BarcodeNumber (length: 100)
        public int WorkstationID { get; set; } // WorkstationID
        public System.DateTime DateCreated { get; set; } // DateCreated
        public System.DateTime DateUpdated { get; set; } // DateUpdated
        public long? StockContainerID { get; set; } // StockContainerID
        public long? ParentStockContainerID { get; set; } // ParentStockContainerID
        public int ProcessName { get; set; } // ProcessName
        public int Result { get; set; } // Result
        public bool IsRescan { get; set; } // IsRescan

        public WP_CashCenter_BarcodeScanHistory()
        {
            IsRescan = false;
        }
    }

}
// </auto-generated>
