// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_Discrepancy
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_Discrepancy
    {
        public long id { get; set; } // id (Primary key)
        public int Level { get; set; } // Level
        public System.DateTime DateCreated { get; set; } // DateCreated
        public bool IsTotal { get; set; } // IsTotal
        public decimal DiscrepancyValue { get; set; } // DiscrepancyValue
        public decimal InitialValue { get; set; } // InitialValue
        public decimal ActualValue { get; set; } // ActualValue
        public decimal CorrectionValue { get; set; } // CorrectionValue
        public decimal? Loc_nr { get; set; } // Loc_nr
        public string Order_ID { get; set; } // Order_ID (length: 20)
        public string MaterialID { get; set; } // MaterialID (length: 10)
        public string ProductCode { get; set; } // ProductCode (length: 10)
        public string CurrencyCode { get; set; } // CurrencyCode (length: 3)
        public int Status { get; set; } // Status
        public System.DateTime DateOccurred { get; set; } // DateOccurred
        public long? TopLevelDiscrepancyID { get; set; } // TopLevelDiscrepancyID
        public long? ContainersBatchID { get; set; } // ContainersBatchID
        public int? StockLocationID { get; set; } // StockLocationID
        public long? StockContainerID { get; set; } // StockContainerID
        public int? QualificationType { get; set; } // QualificationType
        public int? StockOwnerID { get; set; } // StockOwnerID
        public System.DateTime? DateUpdated { get; set; } // DateUpdated
        public int? AuthorID { get; set; } // AuthorID
        public int? EditorID { get; set; } // EditorID
        public System.Guid UID { get; set; } // UID
        public int? DailyHeaderCardID { get; set; } // DailyHeaderCardID
        public decimal DispensedValue { get; set; } // DispensedValue
        public decimal DiscrepancyQuantity { get; set; } // DiscrepancyQuantity
        public decimal InitialQuantity { get; set; } // InitialQuantity
        public decimal ActualQuantity { get; set; } // ActualQuantity
        public decimal DispensedQuantity { get; set; } // DispensedQuantity
        public long? DiscrepancyPreviousID { get; set; } // DiscrepancyPreviousID

        public WP_Discrepancy()
        {
            DiscrepancyValue = 0m;
            InitialValue = 0m;
            CorrectionValue = 0m;
            Status = 2;
            DateOccurred = System.DateTime.Now;
            UID = System.Guid.NewGuid();
            DispensedValue = 0m;
            DiscrepancyQuantity = 0m;
            InitialQuantity = 0m;
            ActualQuantity = 0m;
            DispensedQuantity = 0m;
        }
    }

}
// </auto-generated>
