// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_DynamicsIntegrationSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_DynamicsIntegrationSetting
    {
        public int id { get; set; } // id (Primary key)
        public string GetFilesFolder { get; set; } // GetFilesFolder
        public string PutFilesFolderForExport { get; set; } // PutFilesFolderForExport
        public bool IsImportBaseData { get; set; } // IsImportBaseData
        public bool IsExportCountResults { get; set; } // IsExportCountResults
        public System.TimeSpan? ExportTime { get; set; } // ExportTime
        public string GetFilesFolderForOrderImport { get; set; } // GetFilesFolderForOrderImport
        public bool IsImportOrderData { get; set; } // IsImportOrderData
        public int? OrderServiceType { get; set; } // OrderServiceType
        public bool IsExportOrderUpdate { get; set; } // IsExportOrderUpdate
        public System.TimeSpan OrderUpdateExportTime { get; set; } // OrderUpdateExportTime
        public string PutFilesFolderForOrderUpdateExport { get; set; } // PutFilesFolderForOrderUpdateExport

        public WP_DynamicsIntegrationSetting()
        {
            IsImportBaseData = true;
            IsExportCountResults = true;
            IsImportOrderData = false;
            IsExportOrderUpdate = false;
            PutFilesFolderForOrderUpdateExport = "";
        }
    }

}
// </auto-generated>
