// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_DynamicsIntegrationLocationTypeSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_DynamicsIntegrationLocationTypeSetting
    {
        public string ExternalLocTypeCode { get; set; } // ExternalLocTypeCode (Primary key) (length: 20)
        public string LocationHandlingType { get; set; } // LocationHandlingType (length: 6)
        public string LocationType { get; set; } // LocationType (length: 16)
    }

}
// </auto-generated>
