// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_ExportStatusUpdatesSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_ExportStatusUpdatesSetting
    {
        public int id { get; set; } // id (Primary key)
        public decimal cus_nr { get; set; } // cus_nr
        public string Address { get; set; } // Address (length: 1000)
        public string Login { get; set; } // Login (length: 225)
        public string Password { get; set; } // Password (length: 225)
        public string Email { get; set; } // Email (length: 225)
    }

}
// </auto-generated>
