// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_GroupPermission
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_GroupPermissionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_GroupPermission>
    {
        public WP_GroupPermissionConfiguration()
            : this("dbo")
        {
        }

        public WP_GroupPermissionConfiguration(string schema)
        {
            ToTable("WP_GroupPermission", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Permission_id).HasColumnName(@"Permission_id").HasColumnType("int").IsRequired();
            Property(x => x.Group_id).HasColumnName(@"Group_id").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
