// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_HemaSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_HemaSettingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_HemaSetting>
    {
        public WP_HemaSettingConfiguration()
            : this("dbo")
        {
        }

        public WP_HemaSettingConfiguration(string schema)
        {
            ToTable("WP_HemaSettings", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Settings).HasColumnName(@"Settings").HasColumnType("nvarchar(max)").IsRequired();
            Property(x => x.PreAnnouncementWeekday).HasColumnName(@"PreAnnouncementWeekday").HasColumnType("int").IsOptional();
            Property(x => x.HQEmail).HasColumnName(@"HQEmail").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.GetPreAnnouncementFileFolder).HasColumnName(@"GetPreAnnouncementFileFolder").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.PutMissingPreAnnouncementFolder).HasColumnName(@"PutMissingPreAnnouncementFolder").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.PutLocationReportFolder).HasColumnName(@"PutLocationReportFolder").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.PutCompanyReportFolder).HasColumnName(@"PutCompanyReportFolder").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
        }
    }

}
// </auto-generated>
