// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_IntegrationMasterDataImport_MasterDataOrderProductSetting
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_IntegrationMasterDataImport_MasterDataOrderProductSettingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_IntegrationMasterDataImport_MasterDataOrderProductSetting>
    {
        public WP_IntegrationMasterDataImport_MasterDataOrderProductSettingConfiguration()
            : this("dbo")
        {
        }

        public WP_IntegrationMasterDataImport_MasterDataOrderProductSettingConfiguration(string schema)
        {
            ToTable("WP_IntegrationMasterDataImport_MasterDataOrderProductSetting", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ProductID).HasColumnName(@"ProductID").HasColumnType("nvarchar").IsRequired().HasMaxLength(10);
            Property(x => x.QuantityEnum).HasColumnName(@"QuantityEnum").HasColumnType("int").IsRequired();
            Property(x => x.UnitValue).HasColumnName(@"UnitValue").HasColumnType("decimal").IsRequired().HasPrecision(26,8);
            Property(x => x.JobSettingsID).HasColumnName(@"JobSettingsID").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
