// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_ImportEntitySettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_ImportEntitySetting
    {
        public int id { get; set; } // id (Primary key)
        public string Alias { get; set; } // Alias (length: 255)
        public string ImportTables { get; set; } // ImportTables (length: 255)
        public bool IsImportAvaible { get; set; } // IsImportAvaible

        public WP_ImportEntitySetting()
        {
            IsImportAvaible = false;
        }
    }

}
// </auto-generated>
