// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_Jobs_JobInfo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_Jobs_JobInfoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_Jobs_JobInfo>
    {
        public WP_Jobs_JobInfoConfiguration()
            : this("dbo")
        {
        }

        public WP_Jobs_JobInfoConfiguration(string schema)
        {
            ToTable("WP_Jobs_JobInfo", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.JobTypeName).HasColumnName(@"JobTypeName").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.JobType).HasColumnName(@"JobType").HasColumnType("int").IsRequired();
            Property(x => x.IsAllowMultipleInstances).HasColumnName(@"IsAllowMultipleInstances").HasColumnType("bit").IsRequired();
            Property(x => x.CanBeHidden).HasColumnName(@"CanBeHidden").HasColumnType("bit").IsRequired();
            Property(x => x.Visible).HasColumnName(@"Visible").HasColumnType("bit").IsRequired();
            Property(x => x.IsRunNowAllowed).HasColumnName(@"IsRunNowAllowed").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
