// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_Jobs_JobInstance
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_Jobs_JobInstance
    {
        public int id { get; set; } // id (Primary key)
        public int Status { get; set; } // Status
        public string Comments { get; set; } // Comments
        public int JobInfo_id { get; set; } // JobInfo_id
        public int Server_id { get; set; } // Server_id
        public int StartupType { get; set; } // StartupType
        public int? Settings_id { get; set; } // Settings_id
    }

}
// </auto-generated>
