// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_Jobs_Notification_Attachments
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_Jobs_Notification_AttachmentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_Jobs_Notification_Attachment>
    {
        public WP_Jobs_Notification_AttachmentConfiguration()
            : this("dbo")
        {
        }

        public WP_Jobs_Notification_AttachmentConfiguration(string schema)
        {
            ToTable("WP_Jobs_Notification_Attachments", schema);
            HasKey(x => x.ID);

            Property(x => x.ID).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.NotificationID).HasColumnName(@"NotificationID").HasColumnType("int").IsRequired();
            Property(x => x.FileName).HasColumnName(@"FileName").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.FileContentType).HasColumnName(@"FileContentType").HasColumnType("int").IsRequired();
            Property(x => x.FileContent).HasColumnName(@"FileContent").HasColumnType("varbinary(max)").IsOptional();
        }
    }

}
// </auto-generated>
