// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_LastPackageNumber
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_LastPackageNumberConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_LastPackageNumber>
    {
        public WP_LastPackageNumberConfiguration()
            : this("dbo")
        {
        }

        public WP_LastPackageNumberConfiguration(string schema)
        {
            ToTable("WP_LastPackageNumber", schema);
            HasKey(x => new { x.WP_Order_ID, x.WP_Package_ID });

            Property(x => x.WP_Order_ID).HasColumnName(@"WP_Order_ID").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.WP_Package_ID).HasColumnName(@"WP_Package_ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
        }
    }

}
// </auto-generated>
