// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_OrderingSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_OrderingSetting
    {
        public int id { get; set; } // id (Primary key)
        public bool IsDefault { get; set; } // IsDefault
        public int? ServiceType_id { get; set; } // ServiceType_id
        public int LeadTime { get; set; } // LeadTime
        public int Period { get; set; } // Period
        public int CutOffTime { get; set; } // CutOffTime
        public decimal? MaxValue { get; set; } // MaxValue
        public bool AllowAdHocOrders { get; set; } // AllowAdHocOrders
        public bool Notes { get; set; } // Notes
        public bool Coins { get; set; } // Coins
        public bool Consumables { get; set; } // Consumables
        public bool SpecialCoins { get; set; } // SpecialCoins
        public bool ServicingCodes { get; set; } // ServicingCodes
        public bool PreAnnouncement { get; set; } // PreAnnouncement
        public bool AllowReference { get; set; } // AllowReference
        public bool AllowComments { get; set; } // AllowComments
        public bool BankingHolidays { get; set; } // BankingHolidays
        public bool Saturday { get; set; } // Saturday
        public bool Sunday { get; set; } // Sunday
        public System.DateTime DateCreated { get; set; } // DateCreated
        public System.DateTime DateUpdated { get; set; } // DateUpdated
        public int Author_id { get; set; } // Author_id
        public int Editor_id { get; set; } // Editor_id
        public decimal? Customer_id { get; set; } // Customer_id
        public decimal? Location_id { get; set; } // Location_id
        public bool AllowTotalPreannouncement { get; set; } // AllowTotalPreannouncement
        public bool IgnoreLocationServices { get; set; } // IgnoreLocationServices
        public string LocationCode { get; set; } // LocationCode (length: 16)
        public bool AskForAnother { get; set; } // AskForAnother
        public int? EnabledProducts { get; set; } // EnabledProducts
        public bool Release { get; set; } // Release

        public WP_OrderingSetting()
        {
            AllowTotalPreannouncement = false;
            IgnoreLocationServices = false;
            AskForAnother = false;
            EnabledProducts = 2;
            Release = false;
        }
    }

}
// </auto-generated>
