// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_SyncSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_SyncSetting
    {
        public int id { get; set; } // id (Primary key)
        public int TransportServiceType { get; set; } // TransportServiceType
        public string ExchangeFolder { get; set; } // ExchangeFolder (length: 255)
        public string Login { get; set; } // Login (length: 255)
        public string Password { get; set; } // Password (length: 255)
        public bool SaveLogFilesDuringImport { get; set; } // SaveLogFilesDuringImport
        public bool OnlySavePrimaryKeyInLogFiles { get; set; } // OnlySavePrimaryKeyInLogFiles
    }

}
// </auto-generated>
