// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_StockPositionHistory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_StockPositionHistoryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_StockPositionHistory>
    {
        public WP_StockPositionHistoryConfiguration()
            : this("dbo")
        {
        }

        public WP_StockPositionHistoryConfiguration(string schema)
        {
            ToTable("WP_StockPositionHistory", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CassetteNumber).HasColumnName(@"CassetteNumber").HasColumnType("int").IsRequired();
            Property(x => x.Capacity).HasColumnName(@"Capacity").HasColumnType("int").IsRequired();
            Property(x => x.Quantity).HasColumnName(@"Quantity").HasColumnType("int").IsRequired();
            Property(x => x.Value).HasColumnName(@"Value").HasColumnType("decimal").IsRequired().HasPrecision(18,5);
            Property(x => x.Weight).HasColumnName(@"Weight").HasColumnType("decimal").IsRequired().HasPrecision(18,5);
            Property(x => x.Direction).HasColumnName(@"Direction").HasColumnType("int").IsRequired();
            Property(x => x.Totals).HasColumnName(@"Totals").HasColumnType("tinyint").IsRequired();
            Property(x => x.Indicator).HasColumnName(@"Indicator").HasColumnType("tinyint").IsOptional();
            Property(x => x.CollectIndicatorColor).HasColumnName(@"CollectIndicatorColor").HasColumnType("int").IsOptional();
            Property(x => x.DateCreated).HasColumnName(@"DateCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.MaterialID).HasColumnName(@"MaterialID").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.ProductCode).HasColumnName(@"ProductCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.Machine_id).HasColumnName(@"Machine_id").HasColumnType("int").IsRequired();
            Property(x => x.IsGrandTotal).HasColumnName(@"IsGrandTotal").HasColumnType("bit").IsRequired();
            Property(x => x.CurrencyID).HasColumnName(@"CurrencyID").HasColumnType("nvarchar").IsRequired().HasMaxLength(3);
            Property(x => x.IssueIndicatorColor).HasColumnName(@"IssueIndicatorColor").HasColumnType("int").IsOptional();
            Property(x => x.CassetteExternalNumber).HasColumnName(@"CassetteExternalNumber").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.IsMixed).HasColumnName(@"IsMixed").HasColumnType("bit").IsRequired();
            Property(x => x.MaterialTypeCode).HasColumnName(@"MaterialTypeCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(10);
            Property(x => x.StockPositionID).HasColumnName(@"StockPositionID").HasColumnType("int").IsOptional();
            Property(x => x.IsCounterfeits).HasColumnName(@"IsCounterfeits").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
