// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_StockPositionHistorySettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_StockPositionHistorySetting
    {
        public int id { get; set; } // id (Primary key)
        public double Time { get; set; } // Time
        public int NotesIssuingCassette { get; set; } // NotesIssuingCassette
        public int CoinsIssuingCassette { get; set; } // CoinsIssuingCassette

        public WP_StockPositionHistorySetting()
        {
            NotesIssuingCassette = 1;
            CoinsIssuingCassette = 1;
        }
    }

}
// </auto-generated>
