// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_User_Location
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_User_LocationConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WP_User_Location>
    {
        public WP_User_LocationConfiguration()
            : this("dbo")
        {
        }

        public WP_User_LocationConfiguration(string schema)
        {
            ToTable("WP_User_Location", schema);
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.User_id).HasColumnName(@"User_id").HasColumnType("int").IsRequired();
            Property(x => x.Location_id).HasColumnName(@"Location_id").HasColumnType("numeric").IsRequired().HasPrecision(15,0);
            Property(x => x.FromGroup).HasColumnName(@"FromGroup").HasColumnType("bit").IsRequired();
            Property(x => x.FromClient).HasColumnName(@"FromClient").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
