// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CWC.AutoTests.DataModel
{

    // WP_User_Customer
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class WP_User_Customer
    {
        public int id { get; set; } // id (Primary key)
        public int User_id { get; set; } // User_id
        public decimal Customer_id { get; set; } // Customer_id
        public bool FromGroup { get; set; } // FromGroup
        public bool FromClient { get; set; } // FromClient

        public WP_User_Customer()
        {
            FromClient = false;
        }
    }

}
// </auto-generated>
