//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWC.AutoTests.WebServiceFeedings {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WebServices.WebServiceFeedings", ConfigurationName="WebServiceFeedings.WebServiceFeedingsSoap")]
    public interface WebServiceFeedingsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="SendFeeding", ReplyAction="*")]
        CWC.AutoTests.WebServiceFeedings.SendFeedingResponse SendFeeding(CWC.AutoTests.WebServiceFeedings.SendFeedingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SendFeeding", ReplyAction="*")]
        System.Threading.Tasks.Task<CWC.AutoTests.WebServiceFeedings.SendFeedingResponse> SendFeedingAsync(CWC.AutoTests.WebServiceFeedings.SendFeedingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFeedingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendFeeding", Namespace="WebServices.WebServiceFeedings", Order=0)]
        public CWC.AutoTests.WebServiceFeedings.SendFeedingRequestBody Body;
        
        public SendFeedingRequest() {
        }
        
        public SendFeedingRequest(CWC.AutoTests.WebServiceFeedings.SendFeedingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WebServices.WebServiceFeedings")]
    public partial class SendFeedingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Hash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Content;
        
        public SendFeedingRequestBody() {
        }
        
        public SendFeedingRequestBody(string Login, string Password, string Hash, string Content) {
            this.Login = Login;
            this.Password = Password;
            this.Hash = Hash;
            this.Content = Content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFeedingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendFeedingResponse", Namespace="WebServices.WebServiceFeedings", Order=0)]
        public CWC.AutoTests.WebServiceFeedings.SendFeedingResponseBody Body;
        
        public SendFeedingResponse() {
        }
        
        public SendFeedingResponse(CWC.AutoTests.WebServiceFeedings.SendFeedingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WebServices.WebServiceFeedings")]
    public partial class SendFeedingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidationResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool Warning;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ResponseContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ResponseHash;
        
        public SendFeedingResponseBody() {
        }
        
        public SendFeedingResponseBody(string ValidationResult, bool Warning, string ErrorMessage, string ResponseContent, string ResponseHash) {
            this.ValidationResult = ValidationResult;
            this.Warning = Warning;
            this.ErrorMessage = ErrorMessage;
            this.ResponseContent = ResponseContent;
            this.ResponseHash = ResponseHash;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceFeedingsSoapChannel : CWC.AutoTests.WebServiceFeedings.WebServiceFeedingsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceFeedingsSoapClient : System.ServiceModel.ClientBase<CWC.AutoTests.WebServiceFeedings.WebServiceFeedingsSoap>, CWC.AutoTests.WebServiceFeedings.WebServiceFeedingsSoap {
        
        public WebServiceFeedingsSoapClient() {
        }
        
        public WebServiceFeedingsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceFeedingsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceFeedingsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceFeedingsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CWC.AutoTests.WebServiceFeedings.SendFeedingResponse CWC.AutoTests.WebServiceFeedings.WebServiceFeedingsSoap.SendFeeding(CWC.AutoTests.WebServiceFeedings.SendFeedingRequest request) {
            return base.Channel.SendFeeding(request);
        }
        
        public string SendFeeding(string Login, string Password, string Hash, string Content, out bool Warning, out string ErrorMessage, out string ResponseContent, out string ResponseHash) {
            CWC.AutoTests.WebServiceFeedings.SendFeedingRequest inValue = new CWC.AutoTests.WebServiceFeedings.SendFeedingRequest();
            inValue.Body = new CWC.AutoTests.WebServiceFeedings.SendFeedingRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.Hash = Hash;
            inValue.Body.Content = Content;
            CWC.AutoTests.WebServiceFeedings.SendFeedingResponse retVal = ((CWC.AutoTests.WebServiceFeedings.WebServiceFeedingsSoap)(this)).SendFeeding(inValue);
            Warning = retVal.Body.Warning;
            ErrorMessage = retVal.Body.ErrorMessage;
            ResponseContent = retVal.Body.ResponseContent;
            ResponseHash = retVal.Body.ResponseHash;
            return retVal.Body.ValidationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CWC.AutoTests.WebServiceFeedings.SendFeedingResponse> CWC.AutoTests.WebServiceFeedings.WebServiceFeedingsSoap.SendFeedingAsync(CWC.AutoTests.WebServiceFeedings.SendFeedingRequest request) {
            return base.Channel.SendFeedingAsync(request);
        }
        
        public System.Threading.Tasks.Task<CWC.AutoTests.WebServiceFeedings.SendFeedingResponse> SendFeedingAsync(string Login, string Password, string Hash, string Content) {
            CWC.AutoTests.WebServiceFeedings.SendFeedingRequest inValue = new CWC.AutoTests.WebServiceFeedings.SendFeedingRequest();
            inValue.Body = new CWC.AutoTests.WebServiceFeedings.SendFeedingRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.Hash = Hash;
            inValue.Body.Content = Content;
            return ((CWC.AutoTests.WebServiceFeedings.WebServiceFeedingsSoap)(this)).SendFeedingAsync(inValue);
        }
    }
}
