// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlow.Automation.UI.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SmokeTestsFeature : Xunit.IClassFixture<SmokeTestsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SmokeViewsTests.feature"
#line hidden
        
        public SmokeTestsFeature(SmokeTestsFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Smoke Tests", " \tAs a CWC administrator\r\n\tI want to be able to open any CWC page\r\n\tSo that I hav" +
                    "e access to all functionality\t   ", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.TheoryAttribute(DisplayName="Open all pages on CWC site")]
        [Xunit.TraitAttribute("FeatureTitle", "Smoke Tests")]
        [Xunit.TraitAttribute("Description", "Open all pages on CWC site")]
        [Xunit.InlineDataAttribute("User accounts", new string[0])]
        [Xunit.InlineDataAttribute("Groups", new string[0])]
        [Xunit.InlineDataAttribute("Departments", new string[0])]
        [Xunit.InlineDataAttribute("Set Workstation", new string[0])]
        [Xunit.InlineDataAttribute("Security Settings", new string[0])]
        [Xunit.InlineDataAttribute("Locked IP addresses", new string[0])]
        [Xunit.InlineDataAttribute("Locks", new string[0])]
        [Xunit.InlineDataAttribute("Password Hash", new string[0])]
        [Xunit.InlineDataAttribute("Job instances", new string[0])]
        [Xunit.InlineDataAttribute("Servers", new string[0])]
        [Xunit.InlineDataAttribute("Migration of Contracts", new string[0])]
        [Xunit.InlineDataAttribute("Log Manager", new string[0])]
        [Xunit.InlineDataAttribute("Log Notifications", new string[0])]
        [Xunit.InlineDataAttribute("Test Feedings", new string[0])]
        [Xunit.InlineDataAttribute("Automated Transaction Creation", new string[0])]
        [Xunit.InlineDataAttribute("Archiving Settings", new string[0])]
        [Xunit.InlineDataAttribute("Configuration Keys", new string[0])]
        [Xunit.InlineDataAttribute("Performance Settings", new string[0])]
        [Xunit.InlineDataAttribute("Replication Parties", new string[0])]
        [Xunit.InlineDataAttribute("Replication Packs", new string[0])]
        [Xunit.InlineDataAttribute("Format Settings", new string[0])]
        [Xunit.InlineDataAttribute("Regions", new string[0])]
        [Xunit.InlineDataAttribute("Companies", new string[0])]
        [Xunit.InlineDataAttribute("Service Points", new string[0])]
        [Xunit.InlineDataAttribute("Visit Addresses", new string[0])]
        [Xunit.InlineDataAttribute("Location Services", new string[0])]
        [Xunit.InlineDataAttribute("Location Groups", new string[0])]
        [Xunit.InlineDataAttribute("Location Open Time Settings", new string[0])]
        [Xunit.InlineDataAttribute("Contact persons", new string[0])]
        [Xunit.InlineDataAttribute("Contact Person Notifications", new string[0])]
        [Xunit.InlineDataAttribute("Debtors", new string[0])]
        [Xunit.InlineDataAttribute("Banks", new string[0])]
        [Xunit.InlineDataAttribute("Bank Account", new string[0])]
        [Xunit.InlineDataAttribute("Contracts", new string[0])]
        [Xunit.InlineDataAttribute("Sites", new string[0])]
        [Xunit.InlineDataAttribute("Customer Groups", new string[0])]
        [Xunit.InlineDataAttribute("Market Segments", new string[0])]
        [Xunit.InlineDataAttribute("Location Handling Types", new string[0])]
        [Xunit.InlineDataAttribute("Location Type", new string[0])]
        [Xunit.InlineDataAttribute("CashPoint Types", new string[0])]
        [Xunit.InlineDataAttribute("Products", new string[0])]
        [Xunit.InlineDataAttribute("Product Groups", new string[0])]
        [Xunit.InlineDataAttribute("Materials", new string[0])]
        [Xunit.InlineDataAttribute("Service Types", new string[0])]
        [Xunit.InlineDataAttribute("Package Types", new string[0])]
        [Xunit.InlineDataAttribute("Bag Types", new string[0])]
        [Xunit.InlineDataAttribute("Item Types", new string[0])]
        [Xunit.InlineDataAttribute("Reason Codes", new string[0])]
        [Xunit.InlineDataAttribute("Servicing Codes", new string[0])]
        [Xunit.InlineDataAttribute("Destination Locations", new string[0])]
        [Xunit.InlineDataAttribute("Bag Types Matching Material Types", new string[0])]
        [Xunit.InlineDataAttribute("Bank Holiday Settings", new string[0])]
        [Xunit.InlineDataAttribute("Currencies", new string[0])]
        [Xunit.InlineDataAttribute("Exchange Rates", new string[0])]
        [Xunit.InlineDataAttribute("Cash Center Site Setting", new string[0])]
        [Xunit.InlineDataAttribute("Cash Center Process Setting", new string[0])]
        [Xunit.InlineDataAttribute("CIT Process Settings", new string[0])]
        [Xunit.InlineDataAttribute("Code Formats", new string[0])]
        [Xunit.InlineDataAttribute("Countries", new string[0])]
        [Xunit.InlineDataAttribute("Monitor", new string[0])]
        [Xunit.InlineDataAttribute("Manage", new string[0])]
        [Xunit.InlineDataAttribute("Events", new string[0])]
        [Xunit.InlineDataAttribute("POS Reconciliation", new string[0])]
        [Xunit.InlineDataAttribute("Configure Stock Positions", new string[0])]
        [Xunit.InlineDataAttribute("Automated Order Creation - Optimization Level 1", new string[0])]
        [Xunit.InlineDataAttribute("Bank Number Labels", new string[0])]
        [Xunit.InlineDataAttribute("Stock Value", new string[0])]
        [Xunit.InlineDataAttribute("Transactions", new string[0])]
        [Xunit.InlineDataAttribute("Transaction Details", new string[0])]
        [Xunit.InlineDataAttribute("Status Messages", new string[0])]
        [Xunit.InlineDataAttribute("Errors per Cash point", new string[0])]
        [Xunit.InlineDataAttribute("Errors per Category", new string[0])]
        [Xunit.InlineDataAttribute("Transactions per Cash Point", new string[0])]
        [Xunit.InlineDataAttribute("Collected and Issued Values", new string[0])]
        [Xunit.InlineDataAttribute("Cash Point Uptime", new string[0])]
        [Xunit.InlineDataAttribute("Cash Availability", new string[0])]
        [Xunit.InlineDataAttribute("Residual Percentage", new string[0])]
        [Xunit.InlineDataAttribute("Cash Point Model", new string[0])]
        [Xunit.InlineDataAttribute("Cash Point Status", new string[0])]
        [Xunit.InlineDataAttribute("Category", new string[0])]
        [Xunit.InlineDataAttribute("Status Category", new string[0])]
        [Xunit.InlineDataAttribute("Insurance Settings", new string[0])]
        [Xunit.InlineDataAttribute("Cash Point Reason Codes", new string[0])]
        [Xunit.InlineDataAttribute("Stock View", new string[0])]
        [Xunit.InlineDataAttribute("Order Propositions", new string[0])]
        [Xunit.InlineDataAttribute("Optimization Settings", new string[0])]
        [Xunit.InlineDataAttribute("Order Entry", new string[0])]
        [Xunit.InlineDataAttribute("All Orders", new string[0])]
        [Xunit.InlineDataAttribute("My Orders", new string[0])]
        [Xunit.InlineDataAttribute("Orders per Denomination", new string[0])]
        [Xunit.InlineDataAttribute("Update Order Status Configuration", new string[0])]
        [Xunit.InlineDataAttribute("Email Addresses for New Order Notification", new string[0])]
        [Xunit.InlineDataAttribute("Call Monitor", new string[0])]
        [Xunit.InlineDataAttribute("Task Monitor", new string[0])]
        [Xunit.InlineDataAttribute("Solution time", new string[0])]
        [Xunit.InlineDataAttribute("Number of Calls per status", new string[0])]
        [Xunit.InlineDataAttribute("SLA Performance", new string[0])]
        [Xunit.InlineDataAttribute("Sla Conditions", new string[0])]
        [Xunit.InlineDataAttribute("Call Categories", new string[0])]
        [Xunit.InlineDataAttribute("Requestors", new string[0])]
        [Xunit.InlineDataAttribute("Solution Codes", new string[0])]
        [Xunit.InlineDataAttribute("Failure Codes", new string[0])]
        [Xunit.InlineDataAttribute("Notification Settings", new string[0])]
        [Xunit.InlineDataAttribute("Receive Container", new string[0])]
        [Xunit.InlineDataAttribute("Unpack Deposit", new string[0])]
        [Xunit.InlineDataAttribute("Capture Deposit Specification", new string[0])]
        [Xunit.InlineDataAttribute("Count Deposit", new string[0])]
        [Xunit.InlineDataAttribute("Second Step Counting Form", new string[0])]
        [Xunit.InlineDataAttribute("Exception Management", new string[0])]
        [Xunit.InlineDataAttribute("Inbound Day Closure", new string[0])]
        [Xunit.InlineDataAttribute("Pre-announcements View", new string[0])]
        [Xunit.InlineDataAttribute("Received Containers View", new string[0])]
        [Xunit.InlineDataAttribute("Count orders", new string[0])]
        [Xunit.InlineDataAttribute("Containers Batches View", new string[0])]
        [Xunit.InlineDataAttribute("First step count results view", new string[0])]
        [Xunit.InlineDataAttribute("2nd step count results view", new string[0])]
        [Xunit.InlineDataAttribute("Stock owner count results view", new string[0])]
        [Xunit.InlineDataAttribute("Counting In Progress View", new string[0])]
        [Xunit.InlineDataAttribute("Outbound orders view", new string[0])]
        [Xunit.InlineDataAttribute("Orders Batches", new string[0])]
        [Xunit.InlineDataAttribute("Pick and Pack Transport Units", new string[0])]
        [Xunit.InlineDataAttribute("Outbound containers", new string[0])]
        [Xunit.InlineDataAttribute("Dispatch Orders View", new string[0])]
        [Xunit.InlineDataAttribute("Outbound Day Closure", new string[0])]
        [Xunit.InlineDataAttribute("General Day Closure", new string[0])]
        [Xunit.InlineDataAttribute("Order processing discrepancies", new string[0])]
        [Xunit.InlineDataAttribute("Status for Today", new string[0])]
        [Xunit.InlineDataAttribute("Day Closure History View", new string[0])]
        [Xunit.InlineDataAttribute("Cash Center Reason Codes", new string[0])]
        [Xunit.InlineDataAttribute("Count Identifier", new string[0])]
        [Xunit.InlineDataAttribute("Packing Lines", new string[0])]
        [Xunit.InlineDataAttribute("Streams view", new string[0])]
        [Xunit.InlineDataAttribute("Banknote Series", new string[0])]
        [Xunit.InlineDataAttribute("Seal Container", new string[0])]
        [Xunit.InlineDataAttribute("Unseal Container", new string[0])]
        [Xunit.InlineDataAttribute("Reconcile", new string[0])]
        [Xunit.InlineDataAttribute("Stock Correction", new string[0])]
        [Xunit.InlineDataAttribute("Confirm Storage Device Delivery", new string[0])]
        [Xunit.InlineDataAttribute("Internal Orders", new string[0])]
        [Xunit.InlineDataAttribute("Inventory Checks Page", new string[0])]
        [Xunit.InlineDataAttribute("Take into Storage", new string[0])]
        [Xunit.InlineDataAttribute("Production", new string[0])]
        [Xunit.InlineDataAttribute("Interbank Orders", new string[0])]
        [Xunit.InlineDataAttribute("Stock transactions view", new string[0])]
        [Xunit.InlineDataAttribute("Take into storage orders view", new string[0])]
        [Xunit.InlineDataAttribute("Stock containers view", new string[0])]
        [Xunit.InlineDataAttribute("Value movements view", new string[0])]
        [Xunit.InlineDataAttribute("Container movement view", new string[0])]
        [Xunit.InlineDataAttribute("Actual stock view", new string[0])]
        [Xunit.InlineDataAttribute("Stock value history view", new string[0])]
        [Xunit.InlineDataAttribute("Stock Dashboard", new string[0])]
        [Xunit.InlineDataAttribute("Stock Locations View", new string[0])]
        [Xunit.InlineDataAttribute("Stock Location Types View", new string[0])]
        [Xunit.InlineDataAttribute("Movement types page", new string[0])]
        [Xunit.InlineDataAttribute("Stock Owners View", new string[0])]
        [Xunit.InlineDataAttribute("Visit Monitor", new string[0])]
        [Xunit.InlineDataAttribute("Routes", new string[0])]
        [Xunit.InlineDataAttribute("Search by Routes", new string[0])]
        [Xunit.InlineDataAttribute("Stock Companies", new string[0])]
        [Xunit.InlineDataAttribute("Branches", new string[0])]
        [Xunit.InlineDataAttribute("Vehicles", new string[0])]
        [Xunit.InlineDataAttribute("Perfomance Routes", new string[0])]
        [Xunit.InlineDataAttribute("Missed Visits and Recovered Services", new string[0])]
        [Xunit.InlineDataAttribute("Performance Indicators", new string[0])]
        [Xunit.InlineDataAttribute("Workstations", new string[0])]
        [Xunit.InlineDataAttribute("Cameras", new string[0])]
        [Xunit.InlineDataAttribute("Resource Vehicles", new string[0])]
        [Xunit.InlineDataAttribute("Employees", new string[0])]
        [Xunit.InlineDataAttribute("Production Machines View", new string[0])]
        [Xunit.InlineDataAttribute("Vehicle Types", new string[0])]
        [Xunit.InlineDataAttribute("Person roles", new string[0])]
        [Xunit.InlineDataAttribute("Counting Performance View", new string[0])]
        [Xunit.InlineDataAttribute("Asset Management", new string[0])]
        [Xunit.InlineDataAttribute("Asset Planning", new string[0])]
        [Xunit.InlineDataAttribute("Maintenance Orders", new string[0])]
        [Xunit.InlineDataAttribute("Asset", new string[0])]
        [Xunit.InlineDataAttribute("Asset Stock View", new string[0])]
        [Xunit.InlineDataAttribute("Scan Asset", new string[0])]
        [Xunit.InlineDataAttribute("Region Asset Management Tables", new string[0])]
        [Xunit.InlineDataAttribute("Manufacturer Asset Management Tables", new string[0])]
        [Xunit.InlineDataAttribute("Denomination Asset Management Tables", new string[0])]
        [Xunit.InlineDataAttribute("Maintenance_Reason Asset Management Tables", new string[0])]
        [Xunit.InlineDataAttribute("Failure_Reason Asset Management Tables", new string[0])]
        [Xunit.InlineDataAttribute("Maintenance_Activity Asset Management Tables", new string[0])]
        [Xunit.InlineDataAttribute("Maintenance Locations", new string[0])]
        [Xunit.InlineDataAttribute("Asset Groups", new string[0])]
        [Xunit.InlineDataAttribute("Billing Lines", new string[0])]
        [Xunit.InlineDataAttribute("Cash Flow Information", new string[0])]
        [Xunit.InlineDataAttribute("Reconciliation Frame", new string[0])]
        [Xunit.InlineDataAttribute("Reconciliation View Frame", new string[0])]
        [Xunit.InlineDataAttribute("SETTLEMENT Profiles Settings and Manual Export", new string[0])]
        [Xunit.InlineDataAttribute("Order Pre-announcements", new string[0])]
        [Xunit.InlineDataAttribute("Pre-crediting value view", new string[0])]
        [Xunit.InlineDataAttribute("Invoice Lines", new string[0])]
        [Xunit.InlineDataAttribute("Invoice Configuration Lines", new string[0])]
        [Xunit.InlineDataAttribute("Locations", new string[0])]
        [Xunit.InlineDataAttribute("Pack Lifecycle", new string[0])]
        [Xunit.InlineDataAttribute("Usage Statistics", new string[0])]
        [Xunit.InlineDataAttribute("About WebPortal", new string[0])]
        [Xunit.InlineDataAttribute("Personal details", new string[0])]
        [Xunit.InlineDataAttribute("Change password", new string[0])]
        public virtual void OpenAllPagesOnCWCSite(string page, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Open all pages on CWC site", null, exampleTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 7
 testRunner.When(string.Format("I open \"{0}\" page", page), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
 testRunner.Then("I see page is opened successul", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SmokeTestsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SmokeTestsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
